fishVanilla = [
  "minecraft:cod",
  "minecraft:salmon",
  "minecraft:tropical_fish",
  "minecraft:pufferfish"
]
fishFreshWater = [
  "aquaculture:smallmouth_bass",
  "aquaculture:bluegill",
  "aquaculture:brown_trout",
  "aquaculture:carp",
  "aquaculture:catfish",
  "aquaculture:gar",
  "aquaculture:minnow",
  "aquaculture:muskellunge",
  "aquaculture:perch"
]
fishArid = [
  "aquaculture:bayad",
  "aquaculture:boulti",
  "aquaculture:capitaine",
  "aquaculture:synodontis"
]
fishArtic = [
  "aquaculture:atlantic_cod",
  "aquaculture:blackfish",
  "aquaculture:pacific_halibut",
  "aquaculture:atlantic_halibut",
  "aquaculture:atlantic_herring",
  "aquaculture:pink_salmon",
  "aquaculture:pollock",
  "aquaculture:rainbow_trout"
]
fishSaltWater = [
  "aquaculture:jellyfish",
  "aquaculture:red_grouper",
  "aquaculture:tuna"
]
fishSwamp = [
  "aquaculture:box_turtle",
  "aquaculture:leech",
  "aquaculture:goldfish"
]
fishMushroom = [
  "aquaculture:brown_shrooma",
  "aquaculture:red_shrooma"
]
fishJungle = [
  "aquaculture:arapaima",
  "aquaculture:piranha",
  "aquaculture:tambaqui",
  "aquaculture:arrau_turtle"
]
allFish = (
  fishVanilla + fishFreshWater + fishArid + fishArtic + fishSaltWater +
  fishSwamp + fishMushroom + fishJungle
)
foodOven = [
  'bakery:croissant',
  'bakery:crusty_bread',
  'bakery:bread',
  'bakery:baguette',
  'bakery:toast',
  'bakery:braided_bread',
  'bakery:bun',
  'bakery:vegetable_sandwich',
  'bakery:sandwich',
  'bakery:bread_crate',
  'bakery:linzer_tart',
  'bakery:apple_pie',
  'bakery:glowberry_tart',
  'bakery:chocolate_tart',
  'bakery:bundt_cake',
  'bakery:waffle'
]
foodSmallCookingPot = [
  'bakery:strawberry_jam',
  'bakery:sweetberry_jam',
  'bakery:glowberry_jam',
  'bakery:apple_jam',
  'bakery:chocolate_jam',
  'bakery:chocolate_truffle',
  'bakery:pudding',
  'bakery:jam_roll'
]
foodBakerStation = [
  'bakery:strawberry_cupcake',
  'bakery:sweetberry_cupcake',
  'bakery:apple_cupcake',
  'bakery:strawberry_glazed_cookie',
  'bakery:sweetberry_glazed_cookie',
  'bakery:chocolate_glazed_cookie',
  'bakery:strawberry_cake',
  'bakery:sweetberry_cake',
  'bakery:chocolate_cake'
]
foodGrapevinePot = [
  'vinery:red_grapejuice_wine_bottle',
  'vinery:white_grapejuice_wine_bottle',
  'vinery:taiga_red_grapejuice_bottle',
  'vinery:taiga_white_grapejuice_bottle',
  'vinery:jungle_red_grapejuice_bottle',
  'vinery:jungle_white_grapejuice_bottle',
  'vinery:savanna_red_grapejuice_bottle',
  'vinery:savanna_white_grapejuice_bottle'
]
outfitVinemaker = [
  'vinery:straw_hat',
  'vinery:vinemaker_apron',
  'vinery:vinemaker_leggings',
  'vinery:vinemaker_boots'
]
foodAgingBarrel = [
  'vinery:apple_juice',
  'vinery:apple_wine',
  'vinery:cherry_wine',
  'vinery:magnetic_wine',
  'vinery:noir_wine',
  'vinery:king_danis_wine',
  'vinery:mellohi_wine',
  'vinery:stal_wine',
  'vinery:strad_wine',
  'vinery:solaris_wine',
  'vinery:chorus_wine',
  'vinery:aegis_wine',
  'vinery:clark_wine',
  'vinery:bolvar_wine',
  'vinery:kelp_cider',
  'vinery:chenet_wine',
  'vinery:apple_cider',
  'vinery:jellie_wine',
  'vinery:red_wine',
  'vinery:praetorian_wine',
  'vinery:jo_special_mixture',
  'vinery:cristel_wine',
  'vinery:creepers_crush',
  'vinery:villagers_fright',
  'vinery:glowing_wine',
  'vinery:mead',
  'vinery:bottle_mojang_noir',
  'vinery:eiswein'
]
outfitFur = [
  'meadow:fur_helmet',
  'meadow:fur_chestplate',
  'meadow:fur_leggings',
  'meadow:fur_boots'
]
foodCheesePress = [
  'meadow:cheese_block',
  'meadow:sheep_cheese_block',
  'meadow:grain_cheese_block',
  'meadow:amethyst_cheese_block',
  'meadow:buffalo_cheese_block',
  'meadow:goat_cheese_block',
  'meadow:cheese_sandwich',
  'meadow:cheese_roll',
  'meadow:cheesecake',
  'meadow:cheese_tart'
]
foodCookingPot = [
  'candlelight:tomato_soup',
  'candlelight:mushroom_soup',
  'candlelight:pasta',
  'candlelight:chicken_teriyaki',
  'candlelight:chocolate',
  'candlelight:lasagne',
  'candlelight:chicken',
  'candlelight:pork_ribs',
  'candlelight:salmon_wine'
]
outfitChef = [
  'candlelight:cooking_hat',
  'candlelight:chefs_jacket',
  'candlelight:chefs_pants',
  'candlelight:chefs_boots'
]
foodCookingPan = [
  'candlelight:pancake',
  'candlelight:fricasse',
  'candlelight:roastbeef_carrots',
  'candlelight:beef_wellington',
  'candlelight:pizza',
  'candlelight:cooked_beef',
  'candlelight:bolognese',
  'candlelight:chicken_alfredo',
  'candlelight:lettuce_beef',
  'candlelight:pasta_bolognese',
  'candlelight:pasta_lettuce'
]
foodCraftingTable = [
  'candlelight:tomato_mozzarella_salad',
  'candlelight:veggie_plate',
  'candlelight:lettuce_tomato',
  'candlelight:lettuce_salad',
  'candlelight:beef_tartare',
  'candlelight:beetroot_salad'
]
foodMiniFridge = [
  'beachparty:sweetberry_icecream',
  'beachparty:coconut_icecream',
  'beachparty:chocolate_icecream',
  'beachparty:icecream_chocolate',
  'beachparty:icecream_coconut',
  'beachparty:icecream_cactus',
  'beachparty:icecream_melon',
  'beachparty:icecream_sweetberries',
]
outfitBeach = [
  'beachparty:beach_hat',
  'beachparty:swim_wings',
  'beachparty:trunks',
  'beachparty:crocs'
]
foodTikiBar = [
  'beachparty:chocolate_milkshake',
  'beachparty:coconut_milkshake',
  'beachparty:sweetberry_milkshake',
  'beachparty:honey_cocktail',
  'beachparty:melon_cocktail',
  'beachparty:pumpkin_cocktail',
  'beachparty:cocoa_cocktail',
  'beachparty:sweetberries_cocktail',
  'beachparty:coconut_cocktail'
]
foodDelightful = [
  'delightful:animal_oil_bottle',
  'delightful:ender_nectar',
  'delightful:glow_jelly_bottle',
  'delightful:jelly_bottle',
  'delightful:lavender_tea',
  'delightful:matcha',
  'delightful:nut_butter_bottle',
  'delightful:rock_candy',
  'delightful:salmonberry_gummy',
  'delightful:sinigang',
]
foodAlex = [
  'alexsdelight:acacia_blossom_soup',
  'alexsdelight:kangaroo_pasta',
  'alexsdelight:kangaroo_stew',
  'alexsdelight:lobster_pasta'
]
foodAquaculture = [
  'aquaculture:turtle_soup',
  'aquaculturedelight:baked_pollock_with_carrots',
  'aquaculturedelight:bass_stew',
  'aquaculturedelight:buckling',
  'aquaculturedelight:halaszle',
  'aquaculturedelight:halibut_with_tartar_sauce',
  'aquaculturedelight:jellyfish_jelly',
  'aquaculturedelight:poor_fisher_chowder',
  'aquaculturedelight:rollmops',
  'aquaculturedelight:tuna_spaghetti',
  'aquaculturedelight:unusual_fish_soup'
]
foodFarmersDelight = [
  'farmersdelight:apple_cider',
  'farmersdelight:baked_cod_stew',
  'farmersdelight:beef_stew',
  'farmersdelight:bone_broth',
  'farmersdelight:cabbage_rolls',
  'farmersdelight:chicken_soup',
  'farmersdelight:cooked_rice',
  'farmersdelight:dog_food',
  'farmersdelight:dumplings',
  'farmersdelight:fish_stew',
  'farmersdelight:fried_rice',
  'farmersdelight:glow_berry_custard',
  'farmersdelight:hot_cocoa',
  'farmersdelight:mushroom_rice',
  'farmersdelight:noodle_soup',
  'farmersdelight:pasta_with_meatballs',
  'farmersdelight:pasta_with_mutton_chop',
  'farmersdelight:pumpkin_soup',
  'farmersdelight:ratatouille',
  'farmersdelight:squid_ink_pasta',
  'farmersdelight:stuffed_pumpkin_block',
  'farmersdelight:tomato_sauce',
  'farmersdelight:vegetable_noodles',
  'farmersdelight:vegetable_soup'
]
foodCuisineDelight = [
  'cuisinedelight:ham_fried_rice',
  'cuisinedelight:fried_rice',
  'cuisinedelight:mixed_fried_rice',
  'cuisinedelight:meat_with_seafood',
  'cuisinedelight:meat_with_vegetables',
  'cuisinedelight:seafood_with_vegetables',
  'cuisinedelight:fried_pasta',
  'cuisinedelight:mixed_pasta',
  'cuisinedelight:meat_fried_rice',
  'cuisinedelight:meat_pasta',
  'cuisinedelight:scrambled_egg_and_tomato',
  'cuisinedelight:fried_meat_and_melon',
  'cuisinedelight:meat_platter',
  'cuisinedelight:seafood_fried_rice',
  'cuisinedelight:seafood_pasta',
  'cuisinedelight:vegetable_fried_rice',
  'cuisinedelight:vegetable_pasta',
  'cuisinedelight:seafood_platter',
  'cuisinedelight:vegetable_platter',
  'cuisinedelight:fried_mushroom'
]
floraFoodVanilla = [
  "minecraft:apple",
  "minecraft:bamboo",
  "minecraft:beetroot_seeds",
  "minecraft:brown_mushroom",
  "minecraft:cactus",
  "minecraft:carrot",
  "minecraft:cocoa_beans",
  "minecraft:glow_berries",
  "minecraft:kelp",
  "minecraft:melon_slice",
  "minecraft:potato",
  "minecraft:pumpkin_seeds",
  "minecraft:pumpkin",
  "minecraft:red_mushroom",
  "minecraft:sugar_cane",
  "minecraft:sweet_berries",
  "minecraft:wheat_seeds"
]
floraMiscFood = [
  "alexsmobs:banana",
  "bakery:oat_seeds",
  "bakery:strawberry_seeds",
  "beachparty:coconut",
  "candlelight:lettuce_seeds",
  "candlelight:tomato_seeds",
  "delightful:cantaloupe_slice",
  "delightful:salmonberries",
  "farmersdelight:cabbage_seeds",
  "farmersdelight:onion",
  "farmersdelight:rice",
  "farmersdelight:tomato_seeds",
  "supplementaries:flax_seeds",
  "vinery:jungle_grape_seeds_red",
  "vinery:jungle_grape_seeds_white",
  "vinery:red_grape_seeds",
  "vinery:savanna_grape_seeds_red",
  "vinery:savanna_grape_seeds_white",
  "vinery:taiga_grape_seeds_red",
  "vinery:taiga_grape_seeds_white",
  "vinery:white_grape_seeds"
]
floraFlowerVanilla = [
  "minecraft:allium",
  "minecraft:azure_bluet",
  "minecraft:blue_orchid",
  "minecraft:cornflower",
  "minecraft:dandelion",
  "minecraft:lilac",
  "minecraft:lily_of_the_valley",
  "minecraft:orange_tulip",
  "minecraft:oxeye_daisy",
  "minecraft:peony",
  "minecraft:pink_tulip",
  "minecraft:poppy",
  "minecraft:red_tulip",
  "minecraft:rose_bush",
  "minecraft:sunflower",
  "minecraft:white_tulip",
  "minecraft:wither_rose",
  "minecraft:torchflower_seeds"
]
floraFlowerBiomesoPlenty = [
  "biomesoplenty:blue_hydrangea",
  "biomesoplenty:burning_blossom",
  "biomesoplenty:cattail",
  "biomesoplenty:glowflower",
  "biomesoplenty:goldenrod",
  "biomesoplenty:icy_iris",
  "biomesoplenty:lavender",
  "biomesoplenty:orange_cosmos",
  "biomesoplenty:pink_daffodil",
  "biomesoplenty:pink_hibiscus",
  "biomesoplenty:rose",
  "biomesoplenty:tall_lavender",
  "biomesoplenty:violet",
  "biomesoplenty:waterlily",
  "biomesoplenty:white_petals",
  "biomesoplenty:wildflower",
  "biomesoplenty:wilted_lily"
]
floraFlowerMisc = [
  "alexsmobs:acacia_blossom",
  "candlelight:rose",
  "meadow:alpine_poppy",
  "meadow:delphinium",
  "meadow:enzian",
  "meadow:eriophorum_tall",
  "meadow:eriophorum",
  "meadow:fire_lily",
  "meadow:saxifrage"
]
floraSaplingVanilla = [
  "minecraft:acacia_sapling",
  "minecraft:azalea",
  "minecraft:birch_sapling",
  "minecraft:cherry_sapling",
  "minecraft:dark_oak_sapling",
  "minecraft:jungle_sapling",
  "minecraft:oak_sapling",
  "minecraft:spruce_sapling"
]
floraSaplingModded = [
  "biomesoplenty:dead_sapling",
  "biomesoplenty:fir_sapling",
  "biomesoplenty:flowering_oak_sapling",
  "biomesoplenty:jacaranda_sapling",
  "biomesoplenty:magic_sapling",
  "biomesoplenty:mahogany_sapling",
  "biomesoplenty:maple_sapling",
  "biomesoplenty:orange_autumn_sapling",
  "biomesoplenty:origin_sapling",
  "biomesoplenty:palm_sapling",
  "biomesoplenty:rainbow_birch_sapling",
  "biomesoplenty:redwood_sapling",
  "biomesoplenty:snowblossom_sapling",
  "biomesoplenty:willow_sapling",
  "biomesoplenty:yellow_autumn_sapling",
  "quark:blue_blossom_sapling",
  "quark:lavender_blossom_sapling",
  "quark:orange_blossom_sapling",
  "quark:yellow_blossom_sapling",
  "quark:red_blossom_sapling",
  "beachparty:palm_sapling",
  "meadow:pine_sapling",
  "vinery:cherry_sapling",
  "vinery:apple_tree_sapling"
]
floraMisc = [
  "biomesoplenty:toadstool",
  "biomesoplenty:glowshroom",
  "minecraft:flowering_azalea",
  "minecraft:moss_block",
  "minecraft:moss_carpet",
  "minecraft:pink_petals",
  "minecraft:spore_blossom",
  "minecraft:big_dripleaf",
  "minecraft:sea_pickle",
  "minecraft:lily_pad",
  "biomesoplenty:huge_lily_pad",
  "biomesoplenty:glowing_moss_block",
  "biomesoplenty:glowing_moss_carpet"
]
allFlora = (
  floraFoodVanilla + floraMiscFood + floraFlowerVanilla + floraFlowerBiomesoPlenty
  + floraFlowerMisc + floraSaplingVanilla + floraSaplingModded + floraMisc
)
mineralVanilla = [
  "minecraft:cobblestone",
  "minecraft:mossy_cobblestone",
  "minecraft:cobbled_deepslate",
  "minecraft:diorite",
  "minecraft:granite",
  "minecraft:andesite",
  "minecraft:sandstone",
  "minecraft:red_sandstone",
  "minecraft:calcite",
  "minecraft:dripstone_block",
  "minecraft:pointed_dripstone",
  "minecraft:smooth_basalt",
  "minecraft:tuff",
  "minecraft:obsidian"
]
mineralModded = [
  "create:crimsite",
  "create:asurine",
  "create:veridium",
  "create:ochrum",
  "create:scoria",
  "create:limestone",
  "quark:permafrost",
  "quark:permafrost",
  "quark:myalite",
  "quark:shale",
  "quark:jasper",
  "quark:limestone",
  "meadow:mossy_cobbled_limestone",
  "meadow:cobbled_limestone",
  "biomesoplenty:white_sandstone",
  "biomesoplenty:orange_sandstone",
  "biomesoplenty:black_sandstone",
  "biomesoplenty:dried_salt"
]
mineralOre = [
  "minecraft:coal",
  "minecraft:raw_copper",
  "minecraft:raw_iron",
  "minecraft:amethyst_shard",
  "minecraft:raw_gold",
  "create:raw_zinc",
  "minecraft:redstone",
  "minecraft:lapis_lazuli"
]
mineralCorundum = [
  "quark:red_corundum",
  "quark:red_corundum_cluster",
  "quark:orange_corundum",
  "quark:orange_corundum_cluster",
  "quark:yellow_corundum",
  "quark:yellow_corundum_cluster",
  "quark:green_corundum",
  "quark:green_corundum_cluster",
  "quark:blue_corundum",
  "quark:blue_corundum_cluster",
  "quark:indigo_corundum",
  "quark:indigo_corundum_cluster",
  "quark:violet_corundum",
  "quark:violet_corundum_cluster",
  "quark:white_corundum",
  "quark:white_corundum_cluster",
  "quark:black_corundum",
  "quark:black_corundum_cluster"
]
mineralGemRare = [
  "minecraft:diamond",
  "gemsnjewels:dusk_emerald",
  "gemsnjewels:opal",
  "gemsnjewels:pale_diamond",
  "gemsnjewels:ruby",
  "gemsnjewels:sable_amethyst",
  "gemsnjewels:sapphire"
]
mineralGemCommon = [
  "gemsnjewels:garnet",
  "gemsnjewels:topaz",
  "gemsnjewels:peridot",
  "gemsnjewels:aquamarine",
  "gemsnjewels:zircon",
  "gemsnjewels:alexandrite",
  "gemsnjewels:tanzanite",
  "gemsnjewels:tourmaline",
  "gemsnjewels:spinel",
  "gemsnjewels:black_opal",
  "gemsnjewels:citrine",
  "gemsnjewels:morganite",
  "gemsnjewels:ametrine",
  "gemsnjewels:iolite",
  "gemsnjewels:kunzite",
  "gemsnjewels:jade"
]
hatFlat = [
  "simplehats:beaniejuly",
  "simplehats:beaniefestive",
  "simplehats:beanieeaster",
  "simplehats:beanie",
  "simplehats:baseballhatrgb",
  "simplehats:baseballhatjuly",
  "simplehats:baseballhatfestive",
  "simplehats:baseballhat",
  "simplehats:baseballeaster",
  "simplehats:toy_story_alien",
  "simplehats:beret_ribbon",
  "simplehats:cowboy",
  "simplehats:cowboyrgb",
  "simplehats:explorerhat",
  "simplehats:farmerbrim",
  "simplehats:poofballhat",
  "simplehats:rgbdrinkinhat",
  "simplehats:poofballrgb",
  "simplehats:rgbbowler",
  "simplehats:rgbsmallbowler",
  "simplehats:sombrero",
  "simplehats:summerhat",
  "simplehats:acornhat",
  "simplehats:caddycap",
  "simplehats:beaniespooky",
  "simplehats:beaniergb"
]
hatMedium = [
  "simplehats:floweronhead",
  "simplehats:drinkinhat",
  "simplehats:elfhat",
  "simplehats:crown",
  "simplehats:chefshat",
  "simplehats:bowler",
  "simplehats:bigcrown",
  "simplehats:bigbrain",
  "simplehats:bicorne",
  "simplehats:rgbpartyhat",
  "simplehats:rgbushanka",
  "simplehats:rubbernipple",
  "simplehats:shroomcap",
  "simplehats:swimmer",
  "simplehats:tricorne",
  "simplehats:ushanka",
  "simplehats:zigzagwitchhat",
  "simplehats:azumanga_hat",
  "simplehats:dejiko",
  "simplehats:puchiko",
  "simplehats:policebucket",
  "simplehats:partyhat",
  "simplehats:jesterhat"
]
hatTall = [
  "simplehats:dimmahat",
  "simplehats:topcathat",
  "simplehats:julydouble",
  "simplehats:popehat",
  "simplehats:rgbtoptophathat",
  "simplehats:tophat",
  "simplehats:toptophathat",
  "simplehats:fishing_hat"
]
hatFaceCovering = [
  "simplehats:dragonskullender",
  "simplehats:dragonskull",
  "simplehats:dorkglassesandteeth",
  "simplehats:doctorhat",
  "simplehats:disguise",
  "simplehats:clockface",
  "simplehats:cartoonegg",
  "simplehats:burgerhat",
  "simplehats:breadhat",
  "simplehats:strawberry_hat",
  "simplehats:orange_hat",
  "simplehats:artsy",
  "simplehats:angrymask",
  "simplehats:vikinghatbeard",
  "simplehats:spyzombie",
  "simplehats:festiveribbon",
  "simplehats:finnhood",
  "simplehats:grandmadisguise",
  "simplehats:hockeymask",
  "simplehats:kirbymouthful",
  "simplehats:madscientist",
  "simplehats:megamanhat",
  "simplehats:pinhead",
  "simplehats:redstache",
  "simplehats:santaclaus",
  "simplehats:seaweedhat",
  "simplehats:spiderweb",
  "simplehats:festiveantlers",
  "simplehats:dwarfminerbeard",
  "simplehats:dumhat"
]
hatHeadTopper = [
  "simplehats:palmtree",
  "simplehats:murdered",
  "simplehats:lilbow",
  "simplehats:eggonhead",
  "simplehats:discoball",
  "simplehats:christmascakehat",
  "simplehats:brownbrick",
  "simplehats:bigribbon",
  "simplehats:twilight_doll",
  "simplehats:sandcastle",
  "simplehats:shakehat",
  "simplehats:snowmanbaby",
  "simplehats:springer",
  "simplehats:sprout",
  "simplehats:unicornhorn",
  "simplehats:apple",
  "simplehats:artsy_doll",
  "simplehats:fez",
  "simplehats:milady_doll",
  "simplehats:nyan_doll",
  "simplehats:pom_moog",
  "simplehats:rgbbigribbon",
  "simplehats:questbook",
  "simplehats:presentsstack",
  "simplehats:pohatoe"
]
hatDisguise = [
  "simplehats:frozenhead",
  "simplehats:fishonhead",
  "simplehats:dragonhead",
  "simplehats:egghead",
  "simplehats:easterhead",
  "simplehats:cyclopseye",
  "simplehats:christmastree",
  "simplehats:camera",
  "simplehats:bigstevehead",
  "simplehats:the_noise",
  "simplehats:peppino",
  "simplehats:bucket",
  "simplehats:amalgalichhat",
  "simplehats:alienphil",
  "simplehats:aegishat",
  "simplehats:tvhead",
  "simplehats:tinkerhat",
  "simplehats:jackohat",
  "simplehats:magikarp",
  "simplehats:paperbag",
  "simplehats:paypay",
  "simplehats:plaguedoctor",
  "simplehats:potionhead",
  "simplehats:rgbdragonskull",
  "simplehats:rgbeasterhead",
  "simplehats:rgbfullhelm",
  "simplehats:sonichood",
  "simplehats:spadesoldier",
  "simplehats:stackofeggs",
  "simplehats:hosthat",
  "simplehats:ghostmask",
  "simplehats:fullironhelm"
]
hatAnimal = [
  "simplehats:greenbirb",
  "simplehats:foxhat",
  "simplehats:digger",
  "simplehats:crabonhead",
  "simplehats:bunnyhat",
  "simplehats:chickenonhead",
  "simplehats:chickenhead",
  "simplehats:beehat",
  "simplehats:babyturtle",
  "simplehats:penguinhat",
  "simplehats:pighead",
  "simplehats:rabbitears",
  "simplehats:rabbitonhead",
  "simplehats:ranahat",
  "simplehats:sheep",
  "simplehats:babydolphin",
  "simplehats:teddy_bear",
  "simplehats:penguinbaby",
  "simplehats:icedragonskull",
  "simplehats:horsemask"
]
hatEyewear = [
  "simplehats:eyepatch",
  "simplehats:doubletake",
  "simplehats:dangeresquejuly",
  "simplehats:dangereqsue",
  "simplehats:cheeseslice",
  "simplehats:bluefireeye",
  "simplehats:bigeyes",
  "simplehats:bandanargb",
  "simplehats:bandana",
  "simplehats:monkeyking",
  "simplehats:monocle",
  "simplehats:redeyes",
  "simplehats:rgbsunglasses",
  "simplehats:rock",
  "simplehats:sunglasses",
  "simplehats:sunglassesbig",
  "simplehats:triangleshades",
  "simplehats:circular_glasses",
  "simplehats:lightning_eyes",
  "simplehats:sleepeyemask",
  "simplehats:sport_sunglasses",
  "simplehats:mistletoe",
  "simplehats:grinchhat",
  "simplehats:goggles"
]
hatAroundHead = [
  "simplehats:headshot",
  "simplehats:headphonesblue",
  "simplehats:headbolts",
  "simplehats:halo",
  "simplehats:flowercrown",
  "simplehats:demonhorns",
  "simplehats:cuphead",
  "simplehats:carrotonstick",
  "simplehats:batwinghat",
  "simplehats:chi_ears",
  "simplehats:longfoxears",
  "simplehats:rabi_en_rose",
  "simplehats:antlers",
  "simplehats:winghat",
  "simplehats:nekoears"
]
hatAnimatedDetail = [
  "simplehats:holyhead",
  "simplehats:floatingstar",
  "simplehats:floatinghearts",
  "simplehats:flies",
  "simplehats:flagjuly",
  "simplehats:fireworks",
  "simplehats:fakefire",
  "simplehats:fakeblight",
  "simplehats:candleonhead",
  "simplehats:raincloud",
  "simplehats:burning_m_bison",
  "simplehats:stress",
  "simplehats:smokingpipe",
  "simplehats:simsgem",
  "simplehats:worms_mine",
  "simplehats:rainboworbiters",
  "simplehats:propelhat",
  "simplehats:policesiren"
]
hatAccesories = [
  "simplehats:sausage",
  "simplehats:rednose",
  "simplehats:moreeyes",
  "simplehats:mohawk",
  "simplehats:fro",
  "simplehats:demoneyes",
  "simplehats:dairyqueen",
  "simplehats:candycane",
  "simplehats:camerabeard",
  "simplehats:scouter",
  "simplehats:chalk_stick",
  "simplehats:villagernose",
  "simplehats:supersandhat"
]
allHats = (
  hatFlat + hatMedium + hatTall + hatFaceCovering + hatHeadTopper +
  hatDisguise + hatAnimal + hatEyewear + hatAroundHead +
  hatAnimatedDetail + hatAccesories
)
commonHandheldInstruments = [
  'moa_decor_art:guitarra',
  'moa_decor_art:banyo',
  'moa_decor_art:violin',
  'moa_decor_art:guitarraelectricablanca',
  'moa_decor_art:guitarraelectricagrisclara',
  'moa_decor_art:guitarraelectricagris',
  'moa_decor_art:guitarraelectricanegra',
  'moa_decor_art:guitarraelectricacafe',
  'moa_decor_art:guitarraelectricaroja',
  'moa_decor_art:guitarraelectricanaranja',
  'moa_decor_art:guitarraelectricaamarilla',
  'moa_decor_art:guitarraelectricaverdelima',
  'moa_decor_art:guitarraelectricaverde',
  'moa_decor_art:guitarraelectricacian',
  'moa_decor_art:guitarraelectricaazulclara',
  'moa_decor_art:guitarraelectricaazul',
  'moa_decor_art:guitarraelectricamorada',
  'moa_decor_art:guitarraelectricamagenta',
  'moa_decor_art:guitarraelectricarosa'
]
commonTrophies = [
  'handcrafted:bear_trophy',
  'handcrafted:blaze_trophy',
  'handcrafted:fox_trophy',
  'handcrafted:goat_trophy',
  'handcrafted:pufferfish_trophy',
  'handcrafted:salmon_trophy',
  'handcrafted:silverfish_trophy',
  'handcrafted:skeleton_horse_trophy',
  'handcrafted:spider_trophy'
]
commonSnare = [
  'moa_decor_art:tamborblanco',
  'moa_decor_art:tamborgrisclaro',
  'moa_decor_art:tamborgris',
  'moa_decor_art:tambornegro',
  'moa_decor_art:tamborcafe',
  'moa_decor_art:tamborrojo',
  'moa_decor_art:tambornaranja',
  'moa_decor_art:tamboramarillo',
  'moa_decor_art:tamborverdelima',
  'moa_decor_art:tamborverde',
  'moa_decor_art:tamborcian',
  'moa_decor_art:tamborazulclaro',
  'moa_decor_art:tamborazul',
  'moa_decor_art:tambormorado',
  'moa_decor_art:tambormagenta',
  'moa_decor_art:tamborrosa'
]
commonMariachi = [
  'moa_decor_holidays:mariachiguitarra',
  'moa_decor_holidays:mariachitrompeta',
  'moa_decor_holidays:mariachiviolin',
  'moa_decor_holidays:catrinaroja',
  'moa_decor_holidays:catrinamorada',
  'moa_decor_holidays:catrinacian'
]
commonGraveyard = [
  'moa_decor_holidays:lapida',
  'moa_decor_holidays:lapida_cruz',
  'moa_decor_holidays:fantasma',
  'moa_decor_holidays:esqueletoacostado',
  'moa_decor_holidays:esqueletosentado',
  'moa_decor_holidays:tumba',
  'moa_decor_holidays:tumbaabierta',
  'moa_decor_holidays:tumbaesqueleto',
  'moa_decor_holidays:tumbaesqueletosentado',
  'moa_decor_holidays:jaula',
  'moa_decor_holidays:esqueleto_enjaulado',
  'moa_decor_holidays:bruja_escoba',
  'moa_decor_holidays:zombieacostado',
  'moa_decor_holidays:zombieenterrado',
  'moa_decor_holidays:zombiesaliendotierra',
  'moa_decor_holidays:murcielagocerrado',
  'moa_decor_holidays:murcielagoabierto',
  'moa_decor_holidays:arana_en_telarana',
  'moa_decor_holidays:arana_en_telarana_2'
]
commonBathroom = [
  'moa_decor_bath:inodoro',
  'moa_decor_bath:mingitorio',
  'moa_decor_bath:regadera',
  'moa_decor_bath:llavesderegadera',
  'moa_decor_bath:llavesdebanera',
  'moa_decor_bath:banera',
  'moa_decor_bath:lavabo',
  'moa_decor_bath:lavaboconpedestal',
  'moa_decor_bath:esponjadebano',
  'moa_decor_bath:jabon',
  'moa_decor_bath:soporteparajabon',
  'moa_decor_bath:jabonera',
  'moa_decor_bath:jaboneradepared',
  'moa_decor_bath:tabladeplanchar',
  'moa_decor_bath:tendederoconropamasculina',
  'moa_decor_bath:tendederoconropafemenina',
  'moa_decor_bath:tendederoconsabanas',
  'moa_decor_bath:vasocepillosdedientes',
  'moa_decor_bath:cubetadeagua',
  'moa_decor_bath:secadormanos',
  'moa_decor_bath:destapador',
  'moa_decor_bath:esco',
  'moa_decor_bath:trap',
  'moa_decor_bath:planch',
  'moa_decor_bath:letreropisomojado'
]
commonArts = [
  'moa_decor_art:paletadepintura',
  'moa_decor_art:microfono',
  'moa_decor_art:microfonoenpedestal',
  'moa_decor_art:tecladomusical',
  'moa_decor_art:arpa',
  'moa_decor_art:amplificador',
  'moa_decor_art:mezcladordj',
  'moa_decor_art:tocadiscos',
  'moa_decor_art:acuarelas',
  'moa_decor_art:pincelesenagua',
  'moa_decor_art:martilloycincel',
  'moa_decor_art:maquinadecoser',
  'moa_decor_art:maniqui',
  'moa_decor_art:tijeras'
]
commonFilm = [
  'moa_decor_art:rollodepelicula',
  'moa_decor_art:rollosdepelicula',
  'moa_decor_art:camaradecine',
  'moa_decor_art:claqueta',
  'moa_decor_art:silladedirector',
  'moa_decor_art:reflector',
  'moa_decor_art:gafas_3d'
]
commonFestive= [
  'moa_decor_holidays:clabaza_creeper_nav',
  'moa_decor_holidays:corona_navidena',
  'moa_decor_holidays:santa_claus',
  'moa_decor_holidays:duende_navideno',
  'moa_decor_holidays:duende_navidena',
  'moa_decor_holidays:creeper_nieve',
  'moa_decor_holidays:base_pino_navideno',
  'moa_decor_holidays:pino_navideno',
  'moa_decor_holidays:estrella_navidena',
  'moa_decor_holidays:p_oso_polar_n',
  'moa_decor_holidays:p_galleta_jengibre',
  'moa_decor_holidays:p_galleta_jengibre_n',
  'moa_decor_holidays:leprechaun',
  'moa_decor_holidays:leprechaunolladeoro',
  'moa_decor_holidays:c_pblanco',
  'moa_decor_holidays:c_pcafe',
  'moa_decor_holidays:c_pdorado',
  'moa_decor_holidays:c_pnegro',
  'moa_decor_holidays:conejo_chocolate'
]
commonBooksExploration = [
  'moa_decor_science:telescopio',
  'moa_decor_science:globoterraqueo',
  'moa_decor_science:brujula',
  'moa_decor_science:mapadeltesoro',
  'moa_decor_science:libro',
  'moa_decor_science:libroabierto',
  'moa_decor_science:libroytintero',
  'moa_decor_science:tintero',
  'moa_decor_science:libros',
  'moa_decor_science:librosapilados'
]
commonLab = [
  'moa_decor_science:lupa',
  'moa_decor_science:microscopio',
  'moa_decor_science:calculadora',
  'moa_decor_science:bascula',
  'moa_decor_science:veneno',
  'moa_decor_science:barriltoxico',
  'moa_decor_science:barriltoxicoderramado',
  'moa_decor_science:barrilinflamable',
  'moa_decor_science:barrilinflamablederramado',
  'moa_decor_science:frascodepildoras',
  'moa_decor_science:frascodepildorasabierto',
  'moa_decor_science:botiquindepared',
  'moa_decor_science:lectordesignosvitales'
]
commonPlushSheep = [
  'moa_decor_toys:ovejablanca',
  'moa_decor_toys:ovejagrisclara',
  'moa_decor_toys:ovejagris',
  'moa_decor_toys:ovejanegra',
  'moa_decor_toys:ovejacafe',
  'moa_decor_toys:ovejaroja',
  'moa_decor_toys:ovejanaranja',
  'moa_decor_toys:ovejaamarilla',
  'moa_decor_toys:ovejaverdelima',
  'moa_decor_toys:ovejaverde',
  'moa_decor_toys:ovejacian',
  'moa_decor_toys:ovejaazulclara',
  'moa_decor_toys:ovejaazul',
  'moa_decor_toys:ovejamorada',
  'moa_decor_toys:ovejamagenta',
  'moa_decor_toys:ovejarosa'
]
commonPlushHorse = [
  'moa_decor_toys:caballoblanco',
  'moa_decor_toys:caballocafe',
  'moa_decor_toys:caballocafeosc',
  'moa_decor_toys:caballocastano',
  'moa_decor_toys:caballocrema',
  'moa_decor_toys:caballogris',
  'moa_decor_toys:caballonegro',
  'moa_decor_toys:caballocafe_r',
  'moa_decor_toys:caballocafeosc_r',
  'moa_decor_toys:caballocastano_r',
  'moa_decor_toys:caballocrema_r',
  'moa_decor_toys:caballogris_r',
  'moa_decor_toys:caballonegro_r',
  'moa_decor_toys:caballocafe_m',
  'moa_decor_toys:caballocafeosc_m_1',
  'moa_decor_toys:caballocastano_m',
  'moa_decor_toys:caballocrema_m',
  'moa_decor_toys:caballogris_m',
  'moa_decor_toys:caballonegro_m',
  'moa_decor_toys:caballoblanco_h',
  'moa_decor_toys:caballocafe_h',
  'moa_decor_toys:caballocafeosc_h',
  'moa_decor_toys:caballocastano_h',
  'moa_decor_toys:caballocrema_h',
  'moa_decor_toys:caballogris_h',
  'moa_decor_toys:caballonegro_h',
  'moa_decor_toys:caballocafe_c',
  'moa_decor_toys:caballocafeosc_c',
  'moa_decor_toys:caballocastano_c',
  'moa_decor_toys:caballocrema_c',
  'moa_decor_toys:caballogris_c',
  'moa_decor_toys:caballonegro_c',
  'moa_decor_toys:caballoesqueleto',
  'moa_decor_toys:burro',
  'moa_decor_toys:mula'
]
commonPlushHomeAnimal = [
  'moa_decor_toys:lobo',
  'moa_decor_toys:vaca',
  'moa_decor_toys:gallina',
  'moa_decor_toys:cerdo',
  'moa_decor_toys:abeja'
]
commonPlushRabbit = [
  'moa_decor_toys:conejoblancoynegro',
  'moa_decor_toys:conejoblanco',
  'moa_decor_toys:conejocafe',
  'moa_decor_toys:conejocastano',
  'moa_decor_toys:conejodorado',
  'moa_decor_toys:conejonegro'
]
commonPlushCat = [
  'moa_decor_toys:ocelote',
  'moa_decor_toys:gatoatigrado',
  'moa_decor_toys:gatoblanco',
  'moa_decor_toys:gatobritanico',
  'moa_decor_toys:gatocalico',
  'moa_decor_toys:gatojellie',
  'moa_decor_toys:gatonegro',
  'moa_decor_toys:gatopersa',
  'moa_decor_toys:gatoragdoll',
  'moa_decor_toys:gatosiames',
  'moa_decor_toys:gatotabby',
  'moa_decor_toys:gatotuxedo'
]
commonPlushParrot = [
  'moa_decor_toys:loroazul',
  'moa_decor_toys:lorocian',
  'moa_decor_toys:lorogris',
  'moa_decor_toys:lororojo',
  'moa_decor_toys:loroverde'
]
commonPlushFrog = [
  'moa_decor_toys:ranatemplada',
  'moa_decor_toys:ranacalida',
  'moa_decor_toys:ranahelada'
]
commonPlushLlama = [
  'moa_decor_toys:llamablanca',
  'moa_decor_toys:llamacrema',
  'moa_decor_toys:llamagris',
  'moa_decor_toys:llamacafe'
]
commonPlushWildAnimal = [
  'moa_decor_toys:zorro',
  'moa_decor_toys:zorroblanco',
  'moa_decor_toys:osopolar',
  'moa_decor_toys:panda',
  'moa_decor_toys:murcielago',
  'moa_decor_toys:champivaca',
  'moa_decor_toys:cabra',
  'moa_decor_toys:golemdenieve',
  'moa_decor_toys:camello',
  'moa_decor_toys:sniffer'
]
commonPlushAxolotl = [
  'moa_decor_toys:ajoloteazul',
  'moa_decor_toys:ajolotecafe',
  'moa_decor_toys:ajolotecian',
  'moa_decor_toys:ajolotedorado',
  'moa_decor_toys:ajoloterosa'
]
commonPlushWaterAnimal = [
  'moa_decor_toys:tortugamarina',
  'moa_decor_toys:calamar',
  'moa_decor_toys:calamarbrillante',
  'moa_decor_toys:delfin'
]
commonPlushVillage = [
  'moa_decor_toys:aldeano',
  'moa_decor_toys:aldeanodesierto',
  'moa_decor_toys:aldeanosabana',
  'moa_decor_toys:aldeanoinvierno',
  'moa_decor_toys:aldeanotaiga',
  'moa_decor_toys:aldeanopantano',
  'moa_decor_toys:vendedorambulante',
  'moa_decor_toys:golemdehierro',
  'moa_decor_toys:steve',
  'moa_decor_toys:alex'
]
commonPlushNether = [
  'moa_decor_toys:lavagante',
  'moa_decor_toys:piglin',
  'moa_decor_toys:piglinbruto',
  'moa_decor_toys:piglinzombie',
  'moa_decor_toys:esqueletowither',
  'moa_decor_toys:blaze',
  'moa_decor_toys:ghast',
  'moa_decor_toys:hoglin',
  'moa_decor_toys:zoglin',
  'moa_decor_toys:lavaganteypiglinzombie',
  'moa_decor_toys:gallinaypiglinzombie',
  'moa_decor_toys:cubodemagma'
]
commonPlushZombie = [
  'moa_decor_toys:zombie',
  'moa_decor_toys:zombiemomificado',
  'moa_decor_toys:zombieahogado',
  'moa_decor_toys:aleanozombie',
  'moa_decor_toys:gallinayzombie',
  'moa_decor_toys:gallinayzombiemomificado',
  'moa_decor_toys:gallinayahogado',
  'moa_decor_toys:gallinayjinetealdeanozombie'
]
commonPlushRaid = [
  'moa_decor_toys:bruja',
  'moa_decor_toys:vindicador',
  'moa_decor_toys:invocador',
  'moa_decor_toys:vex',
  'moa_decor_toys:saqueador',
  'moa_decor_toys:devastador',
  'moa_decor_toys:allay',
  'moa_decor_toys:devastadorysaqueador'
]
commonPlushHostileMob = [
  'moa_decor_toys:arana',
  'moa_decor_toys:aranadelascuevas',
  'moa_decor_toys:enderman',
  'moa_decor_toys:slime',
  'moa_decor_toys:creeper',
  'moa_decor_toys:esqueleto',
  'moa_decor_toys:esqueletoglacial',
  'moa_decor_toys:shulker',
  'moa_decor_toys:fantasma',
  'moa_decor_toys:endermite',
  'moa_decor_toys:lepisma',
  'moa_decor_toys:guardian',
  'moa_decor_toys:aranayesqueleto',
  'moa_decor_toys:caballoesqueletoyesqueleto'
]
commonPlushBoss = [
  'moa_decor_toys:guardiananciano',
  'moa_decor_toys:wither',
  'moa_decor_toys:dragondelender',
  'moa_decor_toys:warden'
]
commonToy= [
  'playdate:toy_bench',
  'playdate:dino',
  'playdate:teddy_bear',
  'playdate:ring_tower',
  'playdate:rocking_horse',
  'playdate:toy_boat',
  'playdate:toy_train',
  'playdate:piggy_bank',
  'playdate:music_box',
  'playdate:sock_monkey',
  'playdate:toy_clock',
  'playdate:toy_robot',
  'playdate:wooden_duck',
  'playdate:wooden_soldier',
  'moa_decor_science:pizarra'
]
allCommon = (
  commonHandheldInstruments + commonTrophies + commonSnare + commonMariachi
  + commonGraveyard + commonBathroom + commonArts + commonFilm + commonFestive
  + commonBooksExploration + commonLab + commonPlushSheep + commonPlushHorse
  + commonPlushHomeAnimal + commonPlushRabbit + commonPlushCat + commonPlushParrot
  + commonPlushFrog + commonPlushLlama + commonPlushWildAnimal + commonPlushAxolotl
  + commonPlushWaterAnimal + commonPlushVillage + commonPlushNether + commonPlushZombie
  + commonPlushRaid + commonPlushHostileMob + commonPlushBoss + commonToy
)
rareStatues = [
  'moa_decor_art:esculturaeldavid',
  'moa_decor_art:esculturaelpensador',
  'moa_decor_art:esculturaeldiscobolo',
  'moa_decor_art:esculturavenusdemilo',
  'moa_decor_art:esculturalavictoriodesamotracia',
  'moa_decor_art:esculturamujerconjarra',
  'moa_decor_art:esculturadragonchino',
  'moa_decor_art:esculturachacmool',
  'moa_decor_art:esculturabuda',
  'moa_decor_art:esculturajesuscrucificado'
]
rareMobTrophies = [
  'handcrafted:phantom_trophy',
  'handcrafted:creeper_trophy',
  'handcrafted:skeleton_trophy',
  'handcrafted:evoker_trophy',
  'handcrafted:pillager_trophy',
  'handcrafted:vindicator_trophy',
  'handcrafted:witch_trophy'
]
rarePaintings = [
  'moa_decor_art:pelgrito',
  'moa_decor_art:pgoticoestadounidense',
  'moa_decor_art:plajovendelaperla',
  'moa_decor_art:planocheestrellada',
  'moa_decor_art:plamonalisa',
  'moa_decor_art:pserenatamexicana'
]
rareMisc = [
  'moa_decor_art:pianodecola',
  'moa_decor_art:fonografo',
  'moa_decor_art:maquinadediscos',
  'moa_decor_art:premiogrammy',
  'moa_decor_art:premiooscar',
  'moa_decor_holidays:trineo',
  'moa_decor_holidays:olladeoro'
]
rareOneulFood = [
  'kubejs:oneul_brunch',
  'kubejs:oneul_vanilla_milkshake',
  'kubejs:oneul_canele',
  'kubejs:oneul_tiramisu',
  'kubejs:oneul_sandwich',
  'kubejs:oneul_melon_bread',
  'kubejs:oneul_strawberry_dance'
]
rareOneulPinkBear = [
  'kubejs:oneul_around_midnight',
  'kubejs:oneul_autumn_blessing',
  'kubejs:oneul_bubble',
  'kubejs:oneul_byesummer',
  'kubejs:oneul_cheeseburger',
  'kubejs:oneul_chestnut_latte',
  'kubejs:oneul_chuseok',
  'kubejs:oneul_cloudy_rain',
  'kubejs:oneul_dreamy',
  'kubejs:oneul_flamingo',
  'kubejs:oneul_floating_marshmallow',
  'kubejs:oneul_get_up',
  'kubejs:oneul_gift',
  'kubejs:oneul_happy_reindeer',
  'kubejs:oneul_joy',
  'kubejs:oneul_mistletoe',
  'kubejs:oneul_moonlight',
  'kubejs:oneul_painting',
  'kubejs:oneul_pajama',
  'kubejs:oneul_smile_peach',
  'kubejs:oneul_story',
  'kubejs:oneul_summer_vacation',
  'kubejs:oneul_surf',
  'kubejs:oneul_umbrella',
  'kubejs:oneul_watermelon_fizz',
  'kubejs:oneul_weekend_blanket'
]
rareOneulMisc = [
  'kubejs:oneul_april_daisy',
  'kubejs:oneul_autumn_breeze',
  'kubejs:oneul_chocolate_world',
  'kubejs:oneul_cookie_tree',
  'kubejs:oneul_full_moon',
  'kubejs:oneul_miracle_morning',
  'kubejs:oneul_morning_peppermint',
  'kubejs:oneul_raindrops',
  'kubejs:oneul_roommate',
  'kubejs:oneul_snow_dance',
  'kubejs:oneul_winter_glow'
]
allRareDeco = (
  rareStatues + rareMobTrophies + rarePaintings + rareMisc 
)
allRareMusic = (
  rareOneulFood + rareOneulPinkBear + rareOneulMisc
)
allRare = allRareDeco + allRareMusic
cosmRoyalOutfit = [
  'cosmeticarmoursmod:royal_tunic_black_chestplate',
  'cosmeticarmoursmod:royal_tunic_blue_chestplate',
  'cosmeticarmoursmod:royal_tunic_brown_chestplate',
  'cosmeticarmoursmod:royal_tunic_cyan_chestplate',
  'cosmeticarmoursmod:royal_tunic_green_chestplate',
  'cosmeticarmoursmod:royal_tunic_grey_chestplate',
  'cosmeticarmoursmod:royal_tunic_light_blue_chestplate',
  'cosmeticarmoursmod:royal_tunic_light_grey_chestplate',
  'cosmeticarmoursmod:royal_tunic_lime_chestplate',
  'cosmeticarmoursmod:royal_tunic_magenta_chestplate',
  'cosmeticarmoursmod:royal_tunic_orange_chestplate',
  'cosmeticarmoursmod:royal_tunic_pink_chestplate',
  'cosmeticarmoursmod:royal_tunic_purple_chestplate',
  'cosmeticarmoursmod:royal_tunic_red_chestplate',
  'cosmeticarmoursmod:royal_tunic_white_chestplate',
  'cosmeticarmoursmod:royal_tunic_yellow_chestplate',
  'cosmeticarmoursmod:royal_leggings',
  'cosmeticarmoursmod:royal_boots'
]
cosmSteampunkers = [
  'cosmeticarmoursmod:steampunkers_goggles_helmet',
  'cosmeticarmoursmod:steampunkers_tophat_f_helmet',
  'cosmeticarmoursmod:steampunkers_attire_f_boots',
  'cosmeticarmoursmod:steampunkers_attire_f_chestplate',
  'cosmeticarmoursmod:steampunkers_attire_f_leggings',
  'cosmeticarmoursmod:steampunkers_tophat_helmet',
  'cosmeticarmoursmod:steampunkers_attire_chestplate',
  'cosmeticarmoursmod:steampunkers_attire_leggings',
  'cosmeticarmoursmod:steampunkers_attire_boots',
]
cosmWinterSurvivalist = [
  'cosmeticarmoursmod:blue_ushanka_hat_helmet',
  'cosmeticarmoursmod:winter_survivalist_blue_chestplate',
  'cosmeticarmoursmod:winter_survivalist_blue_leggings',
  'cosmeticarmoursmod:winter_survivalist_blue_boots',
  'cosmeticarmoursmod:brown_ushanka_hat_helmet',
  'cosmeticarmoursmod:winter_survivalist_brown_chestplate',
  'cosmeticarmoursmod:winter_survivalist_brown_leggings',
  'cosmeticarmoursmod:winter_survivalist_brown_boots',
  'cosmeticarmoursmod:grey_ushanka_hat_helmet',
  'cosmeticarmoursmod:winter_survivalist_grey_chestplate',
  'cosmeticarmoursmod:winter_survivalist_grey_leggings',
  'cosmeticarmoursmod:winter_survivalist_grey_boots'
]
cosmAstronaut = [
  'cosmeticarmoursmod:astronaut_helmet',
  'cosmeticarmoursmod:astronaut_chestplate',
  'cosmeticarmoursmod:astronaut_leggings',
  'cosmeticarmoursmod:astronaut_boots'
]
cosmCenturion = [
  'cosmeticarmoursmod:centurions_helmet_helmet',
  'cosmeticarmoursmod:centurion_uniform_chestplate',
  'cosmeticarmoursmod:centurion_uniform_leggings',
  'cosmeticarmoursmod:centurion_uniform_boots'
]
cosmFarmer = [
  'cosmeticarmoursmod:straw_hat_helmet',
  'cosmeticarmoursmod:farmer_attire_boots',
  'cosmeticarmoursmod:farmer_attire_chestplate',
  'cosmeticarmoursmod:farmer_attire_leggings',
]
cosmFisherman = [
  'cosmeticarmoursmod:fishermans_bucket_hat_helmet',
  'cosmeticarmoursmod:fishermans_attire_chestplate',
  'cosmeticarmoursmod:fishermans_attire_leggings',
  'cosmeticarmoursmod:fishermans_attire_boots'
]
cosmGhillieSuit = [
  'cosmeticarmoursmod:ghillie_suit_helmet',
  'cosmeticarmoursmod:ghillie_suit_chestplate',
  'cosmeticarmoursmod:ghillie_suit_leggings',
  'cosmeticarmoursmod:ghillie_suit_boots'
]
cosmMobster = [
  'cosmeticarmoursmod:mobster_helmet',
  'cosmeticarmoursmod:mobster_chestplate',
  'cosmeticarmoursmod:mobster_leggings',
  'cosmeticarmoursmod:mobster_boots',
]
cosmTops = [
  'cosmeticarmoursmod:black_skirt_chestplate',
  'cosmeticarmoursmod:blue_skirt_chestplate',
  'cosmeticarmoursmod:brown_skirt_chestplate',
  'cosmeticarmoursmod:cyan_skirt_chestplate',
  'cosmeticarmoursmod:green_skirt_chestplate',
  'cosmeticarmoursmod:grey_skirt_chestplate',
  'cosmeticarmoursmod:light_blue_skirt_chestplate',
  'cosmeticarmoursmod:light_grey_skirt_chestplate',
  'cosmeticarmoursmod:lime_skirt_chestplate',
  'cosmeticarmoursmod:magenta_skirt_chestplate',
  'cosmeticarmoursmod:orange_skirt_chestplate',
  'cosmeticarmoursmod:pink_skirt_chestplate',
  'cosmeticarmoursmod:purple_skirt_chestplate',
  'cosmeticarmoursmod:red_skirt_chestplate',
  'cosmeticarmoursmod:white_skirt_chestplate',
  'cosmeticarmoursmod:yellow_skirt_chestplate'
]
cosmSkirtBoots = [
  'cosmeticarmoursmod:black_skirt_boots',
  'cosmeticarmoursmod:blue_skirt_boots',
  'cosmeticarmoursmod:brown_skirt_boots',
  'cosmeticarmoursmod:cyan_skirt_boots',
  'cosmeticarmoursmod:green_skirt_boots',
  'cosmeticarmoursmod:grey_skirt_boots',
  'cosmeticarmoursmod:light_blue_skirt_boots',
  'cosmeticarmoursmod:light_grey_skirt_boots',
  'cosmeticarmoursmod:lime_skirt_boots',
  'cosmeticarmoursmod:magenta_skirt_boots',
  'cosmeticarmoursmod:orange_skirt_boots',
  'cosmeticarmoursmod:pink_skirt_boots',
  'cosmeticarmoursmod:purple_skirt_boots',
  'cosmeticarmoursmod:red_skirt_boots',
  'cosmeticarmoursmod:white_skirt_boots',
  'cosmeticarmoursmod:yellow_skirt_boots',
  'cosmeticarmoursmod:black_plaid_skirt_boots',
  'cosmeticarmoursmod:blue_plaid_skirt_boots',
  'cosmeticarmoursmod:brown_plaid_skirt_boots',
  'cosmeticarmoursmod:cyan_plaid_skirt_boots',
  'cosmeticarmoursmod:green_plaid_skirt_boots',
  'cosmeticarmoursmod:grey_plaid_skirt_boots',
  'cosmeticarmoursmod:light_blue_plaid_skirt_boots',
  'cosmeticarmoursmod:light_grey_plaid_skirt_boots',
  'cosmeticarmoursmod:lime_plaid_skirt_boots',
  'cosmeticarmoursmod:magenta_plaid_skirt_boots',
  'cosmeticarmoursmod:orange_plaid_skirt_boots',
  'cosmeticarmoursmod:pink_plaid_skirt_boots',
  'cosmeticarmoursmod:purple_plaid_skirt_boots',
  'cosmeticarmoursmod:red_plaid_skirt_boots',
  'cosmeticarmoursmod:white_plaid_skirt_boots',
  'cosmeticarmoursmod:yellow_plaid_skirt_boots'
]
cosmThighHighSocks = [
  'cosmeticarmoursmod:black_skirt_leggings',
  'cosmeticarmoursmod:blue_skirt_leggings',
  'cosmeticarmoursmod:brown_skirt_leggings',
  'cosmeticarmoursmod:cyan_skirt_leggings',
  'cosmeticarmoursmod:green_skirt_leggings',
  'cosmeticarmoursmod:grey_skirt_leggings',
  'cosmeticarmoursmod:light_blue_skirt_leggings',
  'cosmeticarmoursmod:light_grey_skirt_leggings',
  'cosmeticarmoursmod:lime_skirt_leggings',
  'cosmeticarmoursmod:magenta_skirt_leggings',
  'cosmeticarmoursmod:orange_skirt_leggings',
  'cosmeticarmoursmod:pink_skirt_leggings',
  'cosmeticarmoursmod:purple_skirt_leggings',
  'cosmeticarmoursmod:red_skirt_leggings',
  'cosmeticarmoursmod:white_skirt_leggings',
  'cosmeticarmoursmod:yellow_skirt_leggings',
  'cosmeticarmoursmod:black_plaid_skirt_leggings',
  'cosmeticarmoursmod:blue_plaid_skirt_leggings',
  'cosmeticarmoursmod:brown_plaid_skirt_leggings',
  'cosmeticarmoursmod:cyan_plaid_skirt_leggings',
  'cosmeticarmoursmod:green_plaid_skirt_leggings',
  'cosmeticarmoursmod:grey_plaid_skirt_leggings',
  'cosmeticarmoursmod:light_blue_plaid_skirt_leggings',
  'cosmeticarmoursmod:light_grey_plaid_skirt_leggings',
  'cosmeticarmoursmod:lime_plaid_skirt_leggings',
  'cosmeticarmoursmod:magenta_plaid_skirt_leggings',
  'cosmeticarmoursmod:orange_plaid_skirt_leggings',
  'cosmeticarmoursmod:pink_plaid_skirt_leggings',
  'cosmeticarmoursmod:purple_plaid_skirt_leggings',
  'cosmeticarmoursmod:red_plaid_skirt_leggings',
  'cosmeticarmoursmod:white_plaid_skirt_leggings',
  'cosmeticarmoursmod:yellow_plaid_skirt_leggings'
]
cosmKnightArmors = [
  'cosmeticarmoursmod:blue_knight_helmet_helmet',
  'cosmeticarmoursmod:blue_knight_armour_chestplate',
  'cosmeticarmoursmod:blue_knight_armour_leggings',
  'cosmeticarmoursmod:blue_knight_armour_boots',
  'cosmeticarmoursmod:green_knight_helmet_helmet',
  'cosmeticarmoursmod:green_knight_armour_chestplate',
  'cosmeticarmoursmod:green_knight_armour_leggings',
  'cosmeticarmoursmod:green_knight_armour_boots',
  'cosmeticarmoursmod:orange_knight_helmet_helmet',
  'cosmeticarmoursmod:orange_knight_armour_chestplate',
  'cosmeticarmoursmod:orange_knight_armour_leggings',
  'cosmeticarmoursmod:orange_knight_armour_boots',
  'cosmeticarmoursmod:pink_knight_helmet_helmet',
  'cosmeticarmoursmod:pink_knight_armour_chestplate',
  'cosmeticarmoursmod:pink_knight_armour_leggings',
  'cosmeticarmoursmod:pink_knight_armour_boots',
  'cosmeticarmoursmod:red_knight_helmet_helmet',
  'cosmeticarmoursmod:red_knight_armour_chestplate',
  'cosmeticarmoursmod:red_knight_armour_leggings',
  'cosmeticarmoursmod:red_knight_armour_boots'
]
cosmArchersAttire = [
  'cosmeticarmoursmod:blue_archers_attire_helmet',
  'cosmeticarmoursmod:blue_archers_attire_chestplate',
  'cosmeticarmoursmod:green_archers_attire_helmet',
  'cosmeticarmoursmod:green_archers_attire_chestplate',
  'cosmeticarmoursmod:orange_archers_attire_helmet',
  'cosmeticarmoursmod:orange_archers_attire_chestplate',
  'cosmeticarmoursmod:pink_archers_attire_helmet',
  'cosmeticarmoursmod:pink_archers_attire_chestplate',
  'cosmeticarmoursmod:red_archers_attire_helmet',
  'cosmeticarmoursmod:red_archers_attire_chestplate',
  'cosmeticarmoursmod:archers_attire_leggings',
  'cosmeticarmoursmod:archers_attire_boots'
]
cosmChristmas = [
  'cosmeticarmoursmod:santa_hat_helmet',
  'cosmeticarmoursmod:female_claus_attire_chestplate',
  'cosmeticarmoursmod:female_claus_attire_leggings',
  'cosmeticarmoursmod:female_claus_attire_boots',
  'cosmeticarmoursmod:male_claus_attire_chestplate',
  'cosmeticarmoursmod:male_claus_attire_leggings',
  'cosmeticarmoursmod:male_claus_attire_boots'
]
cosmElves = [
  'cosmeticarmoursmod:christmas_elf_hat_green_helmet',
  'cosmeticarmoursmod:christmas_elf_attire_green_female_chestplate',
  'cosmeticarmoursmod:christmas_elf_attire_green_female_leggings',
  'cosmeticarmoursmod:christmas_elf_attire_green_female_boots',
  'cosmeticarmoursmod:christmas_elf_attire_male_green_chestplate',
  'cosmeticarmoursmod:christmas_elf_attire_male_green_leggings',
  'cosmeticarmoursmod:christmas_elf_attire_male_green_boots',
  'cosmeticarmoursmod:christmas_elf_hat_red_helmet',
  'cosmeticarmoursmod:christmas_elf_attire_red_female_chestplate',
  'cosmeticarmoursmod:christmas_elf_attire_red_female_leggings',
  'cosmeticarmoursmod:christmas_elf_attire_red_female_boots',
  'cosmeticarmoursmod:christmas_elf_attire_red_male_chestplate',
  'cosmeticarmoursmod:christmas_elf_attire_red_male_leggings',
  'cosmeticarmoursmod:christmas_elf_attire_red_male_boots'
]
cosmCrowns = [
  'cosmeticarmoursmod:crown_helmet',
  'cosmeticarmoursmod:diamond_crown_helmet',
  'cosmeticarmoursmod:emerald_crown_helmet',
  'cosmeticarmoursmod:flower_crown_helmet',
  'cosmeticarmoursmod:prismarine_plated_crown_helmet',
  'cosmeticarmoursmod:quartz_crown_helmet',
  'cosmeticarmoursmod:redstone_crown_helmet',
  'cosmeticarmoursmod:amethyst_crown_helmet',
  'cosmeticarmoursmod:amethyst_plated_crown_helmet',
  'cosmeticarmoursmod:rose_gold_plated_crown_helmet'
]
cosmCatEars = [
  'cosmeticarmoursmod:cat_ears_black_helmet',
  'cosmeticarmoursmod:cat_ears_brown_helmet',
  'cosmeticarmoursmod:cat_ears_grey_helmet',
  'cosmeticarmoursmod:cat_ears_orange_helmet',
  'cosmeticarmoursmod:cat_ears_pink_helmet',
  'cosmeticarmoursmod:cat_ears_white_helmet'
]
cosmMasks = [
  'cosmeticarmoursmod:axolotl_mask_helmet',
  'cosmeticarmoursmod:creeper_mask_helmet',
  'cosmeticarmoursmod:guardian_mask_helmet',
  'cosmeticarmoursmod:herobrine_mask_helmet',
  'cosmeticarmoursmod:plain_mask_helmet',
  'cosmeticarmoursmod:pumpkin_mask_helmet',
  'cosmeticarmoursmod:warden_mask_helmet'
]
cosmHalos = [
  'cosmeticarmoursmod:gold_halo_helmet',
  'cosmeticarmoursmod:winged_gold_halo_helmet',
  'cosmeticarmoursmod:angel_halo_helmet',
  'cosmeticarmoursmod:winged_angel_halo_helmet',
  'cosmeticarmoursmod:fallen_angel_halo_helmet',
  'cosmeticarmoursmod:winged_fallen_angel_halo_helmet',
  'cosmeticarmoursmod:rose_gold_halo_helmet',
  'cosmeticarmoursmod:winged_rose_gold_halo_helmet'
]
cosmMiscHats = [
  'cosmeticarmoursmod:antlers_black_helmet',
  'cosmeticarmoursmod:antlers_brown_helmet',
  'cosmeticarmoursmod:antlers_white_helmet',
  'cosmeticarmoursmod:christmas_pudding_beanie_helmet',
  'cosmeticarmoursmod:frankenstein_bolts_helmet',
  'cosmeticarmoursmod:witches_hat_helmet',
  'cosmeticarmoursmod:yorkshire_cap_helmet',
  'cosmeticarmoursmod:saw_accident_helmet'
]
allCosm = (cosmRoyalOutfit + cosmSteampunkers + cosmWinterSurvivalist
  + cosmAstronaut + cosmCenturion + cosmFarmer + cosmFisherman + cosmGhillieSuit
  + cosmMobster + cosmTops + cosmSkirtBoots + cosmThighHighSocks + cosmKnightArmors
  + cosmArchersAttire + cosmChristmas + cosmElves + cosmCrowns + cosmCatEars + cosmMasks
  + cosmHalos + cosmMiscHats)
