MoreJSEvents.villagerTrades((event) => {
  event.removeModdedTrades(["beachparty:barkeeper"], 1)
  event.removeVanillaTrades(["beachparty:barkeeper"], 1)
  event.removeModdedTrades(["beachparty:barkeeper"], 2)
  event.removeVanillaTrades(["beachparty:barkeeper"], 2)
  event.removeModdedTrades(["beachparty:barkeeper"], 3)
  event.removeVanillaTrades(["beachparty:barkeeper"], 3)
  event.removeModdedTrades(["beachparty:barkeeper"], 4)
  event.removeVanillaTrades(["beachparty:barkeeper"], 4)
  event.removeModdedTrades(["beachparty:barkeeper"], 5)
  event.removeVanillaTrades(["beachparty:barkeeper"], 5)
  event.addCustomTrade('beachparty:barkeeper', 1, (offer, entity, random) => {
    offer.setFirstInput('1x kubejs:miles_ticket')
    offer.setOutput('2x minecraft:ice')
    offer.setVillagerExperience(5)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('beachparty:barkeeper', 1, (offer, entity, random) => {
    offer.setFirstInput('1x kubejs:miles_ticket')
    offer.setOutput('8x minecraft:snowball')
    offer.setVillagerExperience(5)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('beachparty:barkeeper', 1, (offer, entity, random) => {
    offer.setFirstInput('12x minecraft:water_bucket')
    offer.setOutput('1x minecraft:emerald')
    offer.setVillagerExperience(5)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('beachparty:barkeeper', 1, (offer, entity, random) => {
    offer.setFirstInput('12x minecraft:powder_snow_bucket')
    offer.setOutput('1x minecraft:emerald')
    offer.setVillagerExperience(5)
    offer.setPriceMultiplier(0.05)
  })
  event.removeModdedTrades(["beachparty:beach_guy"], 1)
  event.removeVanillaTrades(["beachparty:beach_guy"], 1)
  event.removeModdedTrades(["beachparty:beach_guy"], 2)
  event.removeVanillaTrades(["beachparty:beach_guy"], 2)
  event.removeModdedTrades(["beachparty:beach_guy"], 3)
  event.removeVanillaTrades(["beachparty:beach_guy"], 3)
  event.removeModdedTrades(["beachparty:beach_guy"], 4)
  event.removeVanillaTrades(["beachparty:beach_guy"], 4)
  event.removeModdedTrades(["beachparty:beach_guy"], 5)
  event.removeVanillaTrades(["beachparty:beach_guy"], 5)
  event.addCustomTrade('beachparty:beach_guy', 1, (offer, entity, random) => {
    offer.setFirstInput('18x kubejs:miles_ticket')
    offer.setOutput('1x beachparty:sunglasses')
    offer.setVillagerExperience(5)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('beachparty:beach_guy', 1, (offer, entity, random) => {
    offer.setFirstInput('12x kubejs:miles_ticket')
    offer.setOutput('1x beachparty:bikini')
    offer.setVillagerExperience(5)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('beachparty:beach_guy', 1, (offer, entity, random) => {
    offer.setFirstInput('8x kubejs:miles_ticket')
    offer.setOutput('1x beachparty:trunks')
    offer.setVillagerExperience(5)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('beachparty:beach_guy', 1, (offer, entity, random) => {
    offer.setFirstInput('5x kubejs:miles_ticket')
    offer.setOutput('1x beachparty:swim_wings')
    offer.setVillagerExperience(5)
    offer.setPriceMultiplier(0.05)
  })
  event.removeModdedTrades(["brewery:brewer"], 1)
  event.removeVanillaTrades(["brewery:brewer"], 1)
  event.removeModdedTrades(["brewery:brewer"], 2)
  event.removeVanillaTrades(["brewery:brewer"], 2)
  event.removeModdedTrades(["brewery:brewer"], 3)
  event.removeVanillaTrades(["brewery:brewer"], 3)
  event.removeModdedTrades(["brewery:brewer"], 4)
  event.removeVanillaTrades(["brewery:brewer"], 4)
  event.removeModdedTrades(["brewery:brewer"], 5)
  event.removeVanillaTrades(["brewery:brewer"], 5)
  event.addCustomTrade('brewery:brewer', 1, (offer, entity, random) => {
    offer.setFirstInput('2x kubejs:miles_ticket')
    offer.setOutput('3x brewery:hops_seeds')
    offer.setVillagerExperience(5)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('brewery:brewer', 1, (offer, entity, random) => {
    offer.setFirstInput('2x kubejs:miles_ticket')
    offer.setOutput('3x brewery:corn_seeds')
    offer.setVillagerExperience(5)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('brewery:brewer', 1, (offer, entity, random) => {
    offer.setFirstInput('2x kubejs:miles_ticket')
    offer.setOutput('3x brewery:barley_seeds')
    offer.setVillagerExperience(5)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('brewery:brewer', 2, (offer, entity, random) => {
    offer.setFirstInput('4x kubejs:miles_ticket')
    offer.setOutput('2x brewery:hops')
    offer.setVillagerExperience(7)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('brewery:brewer', 2, (offer, entity, random) => {
    offer.setFirstInput('4x kubejs:miles_ticket')
    offer.setOutput('2x brewery:corn')
    offer.setVillagerExperience(7)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('brewery:brewer', 2, (offer, entity, random) => {
    offer.setFirstInput('4x kubejs:miles_ticket')
    offer.setOutput('2x brewery:barley')
    offer.setVillagerExperience(7)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('brewery:brewer', 3, (offer, entity, random) => {
    offer.setFirstInput('1x kubejs:miles_ticket')
    offer.setOutput('1x brewery:pork_knuckle')
    offer.setVillagerExperience(10)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('brewery:brewer', 3, (offer, entity, random) => {
    offer.setFirstInput('1x kubejs:miles_ticket')
    offer.setOutput('6x brewery:pretzel')
    offer.setVillagerExperience(10)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('brewery:brewer', 3, (offer, entity, random) => {
    offer.setFirstInput('1x kubejs:miles_ticket')
    offer.setOutput('1x brewery:sausage')
    offer.setVillagerExperience(10)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('brewery:brewer', 3, (offer, entity, random) => {
    offer.setFirstInput('3x kubejs:miles_ticket')
    offer.setOutput('1x brewery:dumplings')
    offer.setVillagerExperience(10)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('brewery:brewer', 3, (offer, entity, random) => {
    offer.setFirstInput('1x kubejs:miles_ticket')
    offer.setOutput('2x brewery:gingerbread')
    offer.setVillagerExperience(10)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('brewery:brewer', 3, (offer, entity, random) => {
    offer.setFirstInput('1x kubejs:miles_ticket')
    offer.setOutput('1x brewery:mashed_potatoes')
    offer.setVillagerExperience(10)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('brewery:brewer', 4, (offer, entity, random) => {
    offer.setFirstInput('4x kubejs:miles_ticket')
    offer.setOutput('1x brewery:brewfest_trousers')
    offer.setVillagerExperience(10)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('brewery:brewer', 4, (offer, entity, random) => {
    offer.setFirstInput('5x kubejs:miles_ticket')
    offer.setOutput('1x brewery:brewfest_boots')
    offer.setVillagerExperience(10)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('brewery:brewer', 4, (offer, entity, random) => {
    offer.setFirstInput('5x kubejs:miles_ticket')
    offer.setOutput('1x brewery:brewfest_shoes')
    offer.setVillagerExperience(10)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('brewery:brewer', 5, (offer, entity, random) => {
    offer.setFirstInput('10x kubejs:miles_ticket')
    offer.setOutput('1x brewery:brewfest_hat')
    offer.setVillagerExperience(10)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('brewery:brewer', 5, (offer, entity, random) => {
    offer.setFirstInput('10x kubejs:miles_ticket')
    offer.setOutput('1x brewery:brewfest_hat_red')
    offer.setVillagerExperience(10)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('brewery:brewer', 5, (offer, entity, random) => {
    offer.setFirstInput('10x kubejs:miles_ticket')
    offer.setOutput('1x brewery:brewfest_regalia')
    offer.setVillagerExperience(10)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('brewery:brewer', 5, (offer, entity, random) => {
    offer.setFirstInput('10x kubejs:miles_ticket')
    offer.setOutput('1x brewery:brewfest_dress')
    offer.setVillagerExperience(10)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('brewery:brewer', 5, (offer, entity, random) => {
    offer.setFirstInput('10x kubejs:miles_ticket')
    offer.setOutput('1x brewery:brewfest_blouse')
    offer.setVillagerExperience(10)
    offer.setPriceMultiplier(0.05)
  })
  event.removeModdedTrades(["candlelight:cook"], 1)
  event.removeVanillaTrades(["candlelight:cook"], 1)
  event.removeModdedTrades(["candlelight:cook"], 2)
  event.removeVanillaTrades(["candlelight:cook"], 2)
  event.removeModdedTrades(["candlelight:cook"], 3)
  event.removeVanillaTrades(["candlelight:cook"], 3)
  event.removeModdedTrades(["candlelight:cook"], 4)
  event.removeVanillaTrades(["candlelight:cook"], 4)
  event.removeModdedTrades(["candlelight:cook"], 5)
  event.removeVanillaTrades(["candlelight:cook"], 5)
  event.addCustomTrade('candlelight:cook', 1, (offer, entity, random) => {
    offer.setFirstInput('4x candlelight:lettuce')
    offer.setOutput('1x minecraft:emerald')
    offer.setVillagerExperience(2)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('candlelight:cook', 1, (offer, entity, random) => {
    offer.setFirstInput('4x candlelight:tomato')
    offer.setOutput('1x minecraft:emerald')
    offer.setVillagerExperience(2)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('candlelight:cook', 1, (offer, entity, random) => {
    offer.setFirstInput('5x kubejs:miles_ticket')
    offer.setOutput('2x candlelight:tomato_seeds')
    offer.setVillagerExperience(3)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('candlelight:cook', 1, (offer, entity, random) => {
    offer.setFirstInput('4x kubejs:miles_ticket')
    offer.setOutput('2x candlelight:lettuce_seeds')
    offer.setVillagerExperience(2)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('candlelight:cook', 1, (offer, entity, random) => {
    offer.setFirstInput('2x kubejs:miles_ticket')
    offer.setOutput('6x candlelight:butter')
    offer.setVillagerExperience(4)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('candlelight:cook', 2, (offer, entity, random) => {
    offer.setFirstInput('6x kubejs:miles_ticket')
    offer.setOutput('1x candlelight:cooking_pan')
    offer.setVillagerExperience(3)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('candlelight:cook', 2, (offer, entity, random) => {
    offer.setFirstInput('7x kubejs:miles_ticket')
    offer.setOutput('1x candlelight:cooking_pot')
    offer.setVillagerExperience(3)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('candlelight:cook', 2, (offer, entity, random) => {
    offer.setFirstInput('4x kubejs:miles_ticket')
    offer.setOutput('2x candlelight:tool_rack')
    offer.setVillagerExperience(2)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('candlelight:cook', 2, (offer, entity, random) => {
    offer.setFirstInput('1x kubejs:miles_ticket')
    offer.setOutput('2x candlelight:napkin')
    offer.setVillagerExperience(4)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('candlelight:cook', 3, (offer, entity, random) => {
    offer.setFirstInput('4x kubejs:miles_ticket')
    offer.setOutput('1x candlelight:tomato_soup')
    offer.setVillagerExperience(2)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('candlelight:cook', 3, (offer, entity, random) => {
    offer.setFirstInput('2x kubejs:miles_ticket')
    offer.setOutput('1x candlelight:pasta_raw')
    offer.setVillagerExperience(2)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('candlelight:cook', 3, (offer, entity, random) => {
    offer.setFirstInput('1x kubejs:miles_ticket')
    offer.setOutput('1x candlelight:dough')
    offer.setVillagerExperience(1)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('candlelight:cook', 3, (offer, entity, random) => {
    offer.setFirstInput('4x kubejs:miles_ticket')
    offer.setOutput('1x candlelight:mushroom_soup')
    offer.setVillagerExperience(2)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('candlelight:cook', 4, (offer, entity, random) => {
    offer.setFirstInput('1x kubejs:miles_ticket')
    offer.setOutput('2x candlelight:beef_tartare')
    offer.setVillagerExperience(5)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('candlelight:cook', 4, (offer, entity, random) => {
    offer.setFirstInput('1x kubejs:miles_ticket')
    offer.setOutput('2x candlelight:beetroot_salad')
    offer.setVillagerExperience(5)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('candlelight:cook', 4, (offer, entity, random) => {
    offer.setFirstInput('1x kubejs:miles_ticket')
    offer.setOutput('6x candlelight:pancake')
    offer.setVillagerExperience(5)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('candlelight:cook', 4, (offer, entity, random) => {
    offer.setFirstInput('3x kubejs:miles_ticket')
    offer.setOutput('3x candlelight:lettuce_salad')
    offer.setVillagerExperience(5)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('candlelight:cook', 4, (offer, entity, random) => {
    offer.setFirstInput('2x kubejs:miles_ticket')
    offer.setOutput('1x candlelight:table_bowl')
    offer.setVillagerExperience(5)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('candlelight:cook', 5, (offer, entity, random) => {
    offer.setFirstInput('9x kubejs:miles_ticket')
    offer.setOutput('1x candlelight:cooking_hat')
    offer.setVillagerExperience(5)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('candlelight:cook', 5, (offer, entity, random) => {
    offer.setFirstInput('9x kubejs:miles_ticket')
    offer.setOutput('1x candlelight:chocolate_box')
    offer.setVillagerExperience(5)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('candlelight:cook', 5, (offer, entity, random) => {
    offer.setFirstInput('3x kubejs:miles_ticket')
    offer.setOutput('1x candlelight:glass')
    offer.setVillagerExperience(5)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('candlelight:cook', 5, (offer, entity, random) => {
    offer.setFirstInput('1x candlelight:beef_wellington')
    offer.setOutput('1x minecraft:emerald')
    offer.setVillagerExperience(5)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('candlelight:cook', 5, (offer, entity, random) => {
    offer.setFirstInput('1x candlelight:tropical_fish_supreme')
    offer.setOutput('1x minecraft:emerald')
    offer.setVillagerExperience(5)
    offer.setPriceMultiplier(0.05)
  })
  event.removeModdedTrades(["vinery:winemaker"], 1)
  event.removeVanillaTrades(["vinery:winemaker"], 1)
  event.removeModdedTrades(["vinery:winemaker"], 2)
  event.removeVanillaTrades(["vinery:winemaker"], 2)
  event.removeModdedTrades(["vinery:winemaker"], 3)
  event.removeVanillaTrades(["vinery:winemaker"], 3)
  event.removeModdedTrades(["vinery:winemaker"], 4)
  event.removeVanillaTrades(["vinery:winemaker"], 4)
  event.removeModdedTrades(["vinery:winemaker"], 5)
  event.removeVanillaTrades(["vinery:winemaker"], 5)
  event.addCustomTrade('vinery:winemaker', 1, (offer, entity, random) => {
    offer.setFirstInput('5x vinery:red_grape')
    offer.setOutput('1x minecraft:emerald')
    offer.setVillagerExperience(5)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('vinery:winemaker', 1, (offer, entity, random) => {
    offer.setFirstInput('5x vinery:white_grape')
    offer.setOutput('1x minecraft:emerald')
    offer.setVillagerExperience(5)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('vinery:winemaker', 1, (offer, entity, random) => {
    offer.setFirstInput('2x kubejs:miles_ticket')
    offer.setOutput('1x vinery:red_grape_seeds')
    offer.setVillagerExperience(5)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('vinery:winemaker', 1, (offer, entity, random) => {
    offer.setFirstInput('2x kubejs:miles_ticket')
    offer.setOutput('1x vinery:white_grape_seeds')
    offer.setVillagerExperience(5)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('vinery:winemaker', 2, (offer, entity, random) => {
    offer.setFirstInput('1x kubejs:miles_ticket')
    offer.setOutput('2x vinery:wine_bottle')
    offer.setVillagerExperience(7)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('vinery:winemaker', 3, (offer, entity, random) => {
    offer.setFirstInput('3x kubejs:miles_ticket')
    offer.setOutput('1x vinery:flower_box')
    offer.setVillagerExperience(10)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('vinery:winemaker', 3, (offer, entity, random) => {
    offer.setFirstInput('7x kubejs:miles_ticket')
    offer.setOutput('1x vinery:white_grape_crate')
    offer.setVillagerExperience(10)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('vinery:winemaker', 3, (offer, entity, random) => {
    offer.setFirstInput('7x kubejs:miles_ticket')
    offer.setOutput('1x vinery:red_grape_crate')
    offer.setVillagerExperience(10)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('vinery:winemaker', 4, (offer, entity, random) => {
    offer.setFirstInput('4x kubejs:miles_ticket')
    offer.setOutput('1x vinery:basket')
    offer.setVillagerExperience(10)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('vinery:winemaker', 4, (offer, entity, random) => {
    offer.setFirstInput('5x kubejs:miles_ticket')
    offer.setOutput('1x vinery:flower_pot')
    offer.setVillagerExperience(10)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('vinery:winemaker', 4, (offer, entity, random) => {
    offer.setFirstInput('12x kubejs:miles_ticket')
    offer.setOutput('1x vinery:window')
    offer.setVillagerExperience(10)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('vinery:winemaker', 4, (offer, entity, random) => {
    offer.setFirstInput('6x kubejs:miles_ticket')
    offer.setOutput('1x vinery:cherry_beam')
    offer.setVillagerExperience(10)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('vinery:winemaker', 5, (offer, entity, random) => {
    offer.setFirstInput('10x kubejs:miles_ticket')
    offer.setOutput('1x vinery:wine_box')
    offer.setVillagerExperience(10)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('vinery:winemaker', 5, (offer, entity, random) => {
    offer.setFirstInput('6x kubejs:miles_ticket')
    offer.setOutput('1x vinery:lilitu_wine')
    offer.setVillagerExperience(10)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('vinery:winemaker', 5, (offer, entity, random) => {
    offer.setFirstInput('2x kubejs:miles_ticket')
    offer.setOutput('1x vinery:calendar')
    offer.setVillagerExperience(15)
    offer.setPriceMultiplier(0.05)
  })

})