MoreJSEvents.wandererTrades((event) => {
	event.removeVanillaTrades(1)
	event.removeVanillaTrades(2)
	event.removeModdedTrades(1)
	event.removeModdedTrades(2)
})

MoreJSEvents.villagerTrades((event) => {
	event.removeModdedTrades(["villagersplus:horticulturist"], 1)
	event.removeModdedTrades(["villagersplus:horticulturist"], 2)
	event.removeModdedTrades(["villagersplus:horticulturist"], 3)
	event.removeModdedTrades(["villagersplus:horticulturist"], 4)
	event.removeModdedTrades(["villagersplus:horticulturist"], 5)
	event.removeVanillaTrades(["villagersplus:horticulturist"], 1)
	event.removeVanillaTrades(["villagersplus:horticulturist"], 2)
	event.removeVanillaTrades(["villagersplus:horticulturist"], 3)
	event.removeVanillaTrades(["villagersplus:horticulturist"], 4)
	event.removeVanillaTrades(["villagersplus:horticulturist"], 5)

	event.removeModdedTrades(["non_wandering_trader:traveller"], 1)
	event.removeModdedTrades(["non_wandering_trader:traveller"], 2)
	event.removeModdedTrades(["non_wandering_trader:traveller"], 3)
	event.removeModdedTrades(["non_wandering_trader:traveller"], 4)
	event.removeModdedTrades(["non_wandering_trader:traveller"], 5)
	event.removeVanillaTrades(["non_wandering_trader:traveller"], 1)
	event.removeVanillaTrades(["non_wandering_trader:traveller"], 2)
	event.removeVanillaTrades(["non_wandering_trader:traveller"], 3)
	event.removeVanillaTrades(["non_wandering_trader:traveller"], 4)
	event.removeVanillaTrades(["non_wandering_trader:traveller"], 5)
})