MoreJSEvents.villagerTrades((event) => {
  event.removeModdedTrades(["domesticationinnovation:animal_tamer"], 1)
  event.removeVanillaTrades(["domesticationinnovation:animal_tamer"], 1)
  event.removeModdedTrades(["domesticationinnovation:animal_tamer"], 2)
  event.removeVanillaTrades(["domesticationinnovation:animal_tamer"], 2)
  event.removeModdedTrades(["domesticationinnovation:animal_tamer"], 3)
  event.removeVanillaTrades(["domesticationinnovation:animal_tamer"], 3)
  event.removeModdedTrades(["domesticationinnovation:animal_tamer"], 4)
  event.removeVanillaTrades(["domesticationinnovation:animal_tamer"], 4)
  event.removeModdedTrades(["domesticationinnovation:animal_tamer"], 5)
  event.removeVanillaTrades(["domesticationinnovation:animal_tamer"], 5)
  event.addCustomTrade('domesticationinnovation:animal_tamer', 1, (offer, entity, random) => {
    offer.setFirstInput('10x minecraft:tropical_fish')
    offer.setOutput('2x minecraft:emerald')
    offer.setVillagerExperience(2)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('domesticationinnovation:animal_tamer', 1, (offer, entity, random) => {
    offer.setFirstInput('3x minecraft:emerald')
    offer.setOutput('10x minecraft:bone')
    offer.setVillagerExperience(4)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('domesticationinnovation:animal_tamer', 1, (offer, entity, random) => {
    offer.setFirstInput('7x minecraft:hay_block')
    offer.setOutput('1x minecraft:emerald')
    offer.setVillagerExperience(1)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('domesticationinnovation:animal_tamer', 1, (offer, entity, random) => {
    offer.setFirstInput('8x kubejs:miles_ticket')
    offer.setOutput('4x minecraft:cod')
    offer.setVillagerExperience(3)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('domesticationinnovation:animal_tamer', 1, (offer, entity, random) => {
    offer.setFirstInput('4x minecraft:emerald')
    offer.setOutput('2x minecraft:egg')
    offer.setVillagerExperience(3)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('domesticationinnovation:animal_tamer', 1, (offer, entity, random) => {
    offer.setFirstInput('3x minecraft:emerald')
    offer.setOutput('1x domesticationinnovation:feather_on_a_stick')
    offer.setVillagerExperience(3)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('domesticationinnovation:animal_tamer', 2, (offer, entity, random) => {
    offer.setFirstInput('8x kubejs:miles_ticket')
    offer.setOutput('1x minecraft:tropical_fish_bucket')
    offer.setVillagerExperience(7)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('domesticationinnovation:animal_tamer', 2, (offer, entity, random) => {
    offer.setFirstInput('5x domesticationinnovation:collar_tag')
    offer.setOutput('1x minecraft:emerald')
    offer.setVillagerExperience(7)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('domesticationinnovation:animal_tamer', 2, (offer, entity, random) => {
    offer.setFirstInput('4x minecraft:emerald')
    offer.setOutput('12x minecraft:apple')
    offer.setVillagerExperience(7)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('domesticationinnovation:animal_tamer', 2, (offer, entity, random) => {
    offer.setFirstInput('2x minecraft:emerald')
    offer.setOutput('1x domesticationinnovation:pet_bed_magenta')
    offer.setVillagerExperience(7)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('domesticationinnovation:animal_tamer', 2, (offer, entity, random) => {
    offer.setFirstInput('3x minecraft:emerald')
    offer.setOutput('1x domesticationinnovation:deed_of_ownership')
    offer.setVillagerExperience(7)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('domesticationinnovation:animal_tamer', 3, (offer, entity, random) => {
    offer.setFirstInput('4x minecraft:emerald')
    offer.setOutput('1x domesticationinnovation:rotten_apple')
    offer.setVillagerExperience(10)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('domesticationinnovation:animal_tamer', 3, (offer, entity, random) => {
    offer.setFirstInput('3x minecraft:emerald')
    offer.setOutput('1x minecraft:carrot_on_a_stick')
    offer.setVillagerExperience(10)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('domesticationinnovation:animal_tamer', 3, (offer, entity, random) => {
    offer.setFirstInput('3x minecraft:emerald')
    offer.setOutput('2x minecraft:lead')
    offer.setVillagerExperience(10)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('domesticationinnovation:animal_tamer', 3, (offer, entity, random) => {
    offer.setFirstInput('4x minecraft:emerald')
    offer.setOutput('1x minecraft:leather_horse_armor')
    offer.setVillagerExperience(11)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('domesticationinnovation:animal_tamer', 3, (offer, entity, random) => {
    offer.setFirstInput('2x minecraft:emerald')
    offer.setOutput('3x domesticationinnovation:drum')
    offer.setVillagerExperience(11)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('domesticationinnovation:animal_tamer', 3, (offer, entity, random) => {
    offer.setFirstInput('6x minecraft:emerald')
    offer.setOutput('1x minecraft:tadpole_bucket')
    offer.setVillagerExperience(13)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('domesticationinnovation:animal_tamer', 3, (offer, entity, random) => {
    offer.setFirstInput('30x minecraft:emerald')
    offer.setOutput('1x domesticationinnovation:collar_tag')
    offer.setVillagerExperience(10)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('domesticationinnovation:animal_tamer', 4, (offer, entity, random) => {
    offer.setFirstInput('8x minecraft:emerald')
    offer.setOutput('1x minecraft:iron_horse_armor')
    offer.setVillagerExperience(15)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('domesticationinnovation:animal_tamer', 4, (offer, entity, random) => {
    offer.setFirstInput('11x minecraft:emerald')
    offer.setOutput('1x minecraft:axolotl_bucket')
    offer.setVillagerExperience(15)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('domesticationinnovation:animal_tamer', 4, (offer, entity, random) => {
    offer.setFirstInput('26x minecraft:emerald')
    offer.setOutput('1x minecraft:turtle_egg')
    offer.setVillagerExperience(15)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('domesticationinnovation:animal_tamer', 4, (offer, entity, random) => {
    offer.setFirstInput('60x minecraft:emerald')
    offer.setOutput('1x domesticationinnovation:collar_tag')
    offer.setVillagerExperience(15)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('domesticationinnovation:animal_tamer', 5, (offer, entity, random) => {
    offer.setFirstInput('13x minecraft:emerald')
    offer.setOutput('1x minecraft:golden_horse_armor')
    offer.setVillagerExperience(18)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('domesticationinnovation:animal_tamer', 5, (offer, entity, random) => {
    offer.setFirstInput('21x minecraft:emerald')
    offer.setOutput('1x minecraft:scute')
    offer.setVillagerExperience(18)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('domesticationinnovation:animal_tamer', 5, (offer, entity, random) => {
    offer.setFirstInput('64x minecraft:emerald')
    offer.setOutput('1x domesticationinnovation:collar_tag')
    offer.setVillagerExperience(20)
    offer.setPriceMultiplier(0.05)
  })
  event.addCustomTrade('domesticationinnovation:animal_tamer', 5, (offer, entity, random) => {
    offer.setFirstInput('12x minecraft:emerald')
    offer.setOutput('1x minecraft:enchanted_book')
    offer.setVillagerExperience(18)
    offer.setPriceMultiplier(0.02)
  })

})