ItemEvents.tooltip(event => {
  event.add(
    [
      'pamhc2foodextended:sushiitem', 
      'aquaculture:sushi', 
      'pamhc2foodextended:californiarollitem', 
      'farmersdelight:salmon_roll', 
      'farmersdelight:cod_roll', 
      'farmersdelight:kelp_roll_slice', 
      'aquaculturedelight:raw_fish_fillet_roll', 
      'moa_decor_cookery:sushi', 
      'farmersdelight:rice_roll_medley_block', 
      'aquaculture:algae', 
      'aquaculture:lockbox', 
      'aquaculture:treasure_chest', 
      'minecraft:trident', 
      'aquaculture:neptunium_ingot'
    ],
    [
      'You can buy this item from Sam'
    ])
  event.add(
    [
      'aquaculture:bluegill', 
      'aquaculture:perch', 
      'aquaculture:minnow', 
      'aquaculture:smallmouth_bass', 
      'aquaculture:brown_trout', 
      'aquaculture:carp', 
      'aquaculture:gar', 
      'aquaculture:muskellunge', 
      'aquaculture:catfish'
    ],
    [
      'You can sell this item to Sam during Spring'
    ])
  event.add(
    [
      'aquaculture:piranha', 
      'aquaculture:leech', 
      'aquaculture:tambaqui', 
      'aquaculture:box_turtle', 
      'aquaculture:capitaine', 
      'aquaculture:arapaima'
    ],
    [
      'You can sell this item to Sam during Summer'
    ])
  event.add(
    [
      'aquaculture:brown_shrooma', 
      'aquaculture:red_shrooma', 
      'aquaculture:synodontis', 
      'aquaculture:boulti', 
      'aquaculture:bayad', 
      'aquaculture:arrau_turtle'
    ],
    [
      'You can sell this item to Sam during Fall'
    ])
  event.add(
    [
      'aquaculture:atlantic_herring', 
      'aquaculture:blackfish', 
      'alexsmobs:flying_fish', 
      'alexsmobs:blobfish', 
      'aquaculture:pollock', 
      'aquaculture:jellyfish', 
      'aquaculture:atlantic_cod', 
      'aquaculture:pacific_halibut', 
      'aquaculture:atlantic_halibut', 
      'aquaculture:pink_salmon', 
      'aquaculture:rainbow_trout', 
      'aquaculture:red_grouper', 
      'aquaculture:tuna'
    ],
    [
      'You can sell this item to Sam during Winter'
    ])

})