ItemEvents.tooltip(event => {
  event.add('minecraft:white_candle', ["Enchant Influences: Unbreaking"])
  event.add('minecraft:orange_candle', ["Enchant Influences: Fire Protection"])
  event.add('minecraft:magenta_candle', ["Enchant Influences: Knockback, Punch"])
  event.add('minecraft:light_blue_candle', ["Enchant Influences: Feather Falling"])
  event.add('minecraft:yellow_candle', ["Enchant Influences: Looting, Fortune, Luck of the Sea"])
  event.add('minecraft:lime_candle', ["Enchant Influences: Blast Protection"])
  event.add('minecraft:pink_candle', ["Enchant Influences: Silk Touch, Channeling"])
  event.add('minecraft:gray_candle', ["Enchant Influences: Bane of Arhtropods"])
  event.add('minecraft:light_gray_candle', ["Enchant Influences: Protection"])
  event.add('minecraft:cyan_candle', ["Enchant Influences: Respiration, Loyalty, Infinity"])
  event.add('minecraft:purple_candle', ["Enchant Influences: Sweeping Edge, Multishot"])
  event.add('minecraft:blue_candle', ["Enchant Influences: Efficiency, Sharpness, Lure, Power, Impaling, Quick Charge"])
  event.add('minecraft:brown_candle', ["Enchant Influences: Aqua Affinity, Depth Strider, Riptide"])
  event.add('minecraft:green_candle', ["Enchant Influences: Thorns, Piercing"])
  event.add('minecraft:red_candle', ["Enchant Influences: Fire Aspect, Flame"])
  event.add('minecraft:black_candle', ["Enchant Influences: Smite, Projectile Protection"])
})