buildingMaterials = [
    # not in quests
    "minecraft:dirt",
    "minecraft:cobblestone",
    "minecraft:cobbled_deepslate",
    "minecraft:diorite",
    "minecraft:granite",
    "minecraft:andesite",
    "minecraft:gravel",
    "minecraft:sand",
    "minecraft:sandstone",
    "minecraft:red_sand",
    "minecraft:red_sandstone",
    "minecraft:magma_block",
    "minecraft:soul_sand",
    "minecraft:soul_soil",
    "minecraft:netherrack",
    "minecraft:moss_block",
    "minecraft:ice",
    "minecraft:clay",

    # in quests
    "minecraft:calcite",
    "minecraft:dripstone_block",
    "minecraft:blackstone",

    "create:crimsite",
    "create:asurine",
    "create:veridium",

    "minecraft:smooth_basalt",
    "create:ochrum",
    "create:scoria",

    "create:limestone",

    "create:scorchia",

    # terracotta and concrete
    "minecraft:black_terracotta",
    "minecraft:blue_terracotta",
    "minecraft:brown_terracotta",
    "minecraft:cyan_terracotta",
    "minecraft:gray_terracotta",
    "minecraft:green_terracotta",
    "minecraft:light_blue_terracotta",
    "minecraft:light_gray_terracotta",
    "minecraft:lime_terracotta",
    "minecraft:magenta_terracotta",
    "minecraft:orange_terracotta",
    "minecraft:pink_terracotta",
    "minecraft:purple_terracotta",
    "minecraft:red_terracotta",
    "minecraft:terracotta",
    "minecraft:white_terracotta",
    "minecraft:yellow_terracotta",
    "minecraft:black_concrete",
    "minecraft:black_concrete_powder",
    "minecraft:blue_concrete",
    "minecraft:blue_concrete_powder",
    "minecraft:brown_concrete",
    "minecraft:brown_concrete_powder",
    "minecraft:cyan_concrete",
    "minecraft:cyan_concrete_powder",
    "minecraft:gray_concrete",
    "minecraft:gray_concrete_powder",
    "minecraft:green_concrete",
    "minecraft:green_concrete_powder",
    "minecraft:light_blue_concrete",
    "minecraft:light_blue_concrete_powder",
    "minecraft:light_gray_concrete",
    "minecraft:light_gray_concrete_powder",
    "minecraft:lime_concrete",
    "minecraft:lime_concrete_powder",
    "minecraft:magenta_concrete",
    "minecraft:magenta_concrete_powder",
    "minecraft:orange_concrete",
    "minecraft:orange_concrete_powder",
    "minecraft:pink_concrete",
    "minecraft:pink_concrete_powder",
    "minecraft:purple_concrete",
    "minecraft:purple_concrete_powder",
    "minecraft:red_concrete",
    "minecraft:red_concrete_powder",
    "minecraft:white_concrete",
    "minecraft:white_concrete_powder",
    "minecraft:yellow_concrete",
    "minecraft:yellow_concrete_powder",
    "minecraft:snow_block"
]