itemKey = 'item'
countKey = 'count'

pricing = {
  1: [
    {itemKey: "farmersdelight:hot_cocoa"},
    {itemKey: "farmersdelight:apple_cider"},
    {itemKey: "farmersdelight:tomato_sauce", countKey: 4},
    {itemKey: "farmersdelight:cooked_rice"},
    {itemKey: "farmersdelight:vegetable_soup"},
    {itemKey: "farmersdelight:mushroom_rice"},
    {itemKey: "farmersdelight:ratatouille"},
    {itemKey: "delightful:matcha"},
    {itemKey: "delightful:animal_oil_bottle"},
    {itemKey: "delightful:lavender_tea"},
    {itemKey: "delightful:jelly_bottle"},
    {itemKey: "delightful:nut_butter_bottle"},
    {itemKey: "cuisinedelight:fried_rice"},
    {itemKey: "cuisinedelight:fried_pasta"},
    {itemKey: "cuisinedelight:meat_platter"},
    {itemKey: "cuisinedelight:seafood_platter"},
    {itemKey: "cuisinedelight:vegetable_platter"},
    {itemKey: "cuisinedelight:fried_mushroom"},
    {itemKey: "vinery:apple_juice"},
    {itemKey: "vinery:red_grapejuice_wine_bottle"},
    {itemKey: "vinery:white_grapejuice_wine_bottle"},
    {itemKey: "vinery:taiga_red_grapejuice_bottle"},
    {itemKey: "vinery:taiga_white_grapejuice_bottle"},
    {itemKey: "vinery:jungle_red_grapejuice_bottle"},
    {itemKey: "vinery:jungle_white_grapejuice_bottle"},
    {itemKey: "vinery:savanna_red_grapejuice_bottle"},
    {itemKey: "vinery:savanna_white_grapejuice_bottle"},
    {itemKey: "candlelight:beetroot_salad", countKey: 2},
    {itemKey: "candlelight:beef_tartare", countKey: 2},
    {itemKey: "candlelight:lettuce_tomato", countKey: 2},
    {itemKey: "candlelight:veggie_plate", countKey: 2},
    {itemKey: "candlelight:pancake", countKey: 6},
    {itemKey: "candlelight:tomato_mozzarella_salad", countKey: 2},
    {itemKey: "bakery:strawberry_jam"},
    {itemKey: "bakery:sweetberry_jam"},
    {itemKey: "bakery:glowberry_jam"},
    {itemKey: "bakery:apple_jam"},
    {itemKey: "bakery:croissant", countKey: 8},
    {itemKey: "bakery:crusty_bread", countKey: 4},
    {itemKey: "bakery:bread", countKey: 3},
    {itemKey: "bakery:baguette", countKey: 3},
    {itemKey: "bakery:toast", countKey: 3},
    {itemKey: "bakery:braided_bread", countKey: 4},
    {itemKey: "bakery:bun", countKey: 5},
    {itemKey: "bakery:vegetable_sandwich"},
    {itemKey: "bakery:sandwich"},
    {itemKey: "bakery:bundt_cake"},
    {itemKey: "bakery:linzer_tart"},
    {itemKey: "bakery:apple_pie"},
    {itemKey: "bakery:glowberry_tart"},
    {itemKey: "bakery:jam_roll", countKey: 4},
    {itemKey: "bakery:waffle", countKey: 6},
    {itemKey: "bakery:chocolate_truffle", countKey: 4}
  ],
  2: [
    {itemKey: "aquaculturedelight:jellyfish_jelly"},
    {itemKey: "farmersdelight:glow_berry_custard"},
    {itemKey: "farmersdelight:dumplings", countKey: 2},
    {itemKey: "farmersdelight:cabbage_rolls"},
    {itemKey: "farmersdelight:bone_broth"},
    {itemKey: "farmersdelight:beef_stew"},
    {itemKey: "farmersdelight:chicken_soup"},
    {itemKey: "farmersdelight:fish_stew"},
    {itemKey: "farmersdelight:fried_rice"},
    {itemKey: "farmersdelight:pumpkin_soup"},
    {itemKey: "farmersdelight:baked_cod_stew"},
    {itemKey: "farmersdelight:noodle_soup"},
    {itemKey: "farmersdelight:pasta_with_meatballs"},
    {itemKey: "farmersdelight:pasta_with_mutton_chop"},
    {itemKey: "farmersdelight:vegetable_noodles"},
    {itemKey: "farmersdelight:squid_ink_pasta"},
    {itemKey: "farmersdelight:dog_food"},
    {itemKey: "delightful:salmonberry_gummy"},
    {itemKey: "delightful:glow_jelly_bottle"},
    {itemKey: "alexsdelight:kangaroo_stew"},
    {itemKey: "alexsdelight:acacia_blossom_soup"},
    {itemKey: "alexsdelight:lobster_pasta"},
    {itemKey: "alexsdelight:kangaroo_pasta"},
    {itemKey: "cuisinedelight:ham_fried_rice"},
    {itemKey: "cuisinedelight:meat_with_seafood"},
    {itemKey: "cuisinedelight:meat_with_vegetables"},
    {itemKey: "cuisinedelight:seafood_with_vegetables"},
    {itemKey: "cuisinedelight:meat_fried_rice"},
    {itemKey: "cuisinedelight:meat_pasta"},
    {itemKey: "cuisinedelight:seafood_fried_rice"},
    {itemKey: "cuisinedelight:seafood_pasta"},
    {itemKey: "cuisinedelight:vegetable_fried_rice"},
    {itemKey: "cuisinedelight:vegetable_pasta"},
    {itemKey: "cuisinedelight:fried_meat_and_melon"},
    {itemKey: "cuisinedelight:scrambled_egg_and_tomato"},
    {itemKey: "vinery:cherry_wine"},
    {itemKey: "vinery:noir_wine"},
    {itemKey: "vinery:apple_cider"},
    {itemKey: "vinery:red_wine"},
    {itemKey: "vinery:praetorian_wine"},
    {itemKey: "vinery:creepers_crush"},
    {itemKey: "vinery:glowing_wine"},
    {itemKey: "vinery:bottle_mojang_noir"},
    {itemKey: "candlelight:chicken_teriyaki", countKey: 4},
    {itemKey: "candlelight:lettuce_salad", countKey: 3},
    {itemKey: "candlelight:pasta_lettuce"},
    {itemKey: "candlelight:chocolate", countKey: 4},
    {itemKey: "bakery:chocolate_jam"},
    {itemKey: "bakery:strawberry_cake"},
    {itemKey: "bakery:sweetberry_cake"},
    {itemKey: "bakery:chocolate_cake"},
    {itemKey: "bakery:pudding"},
    {itemKey: "bakery:chocolate_tart"},
    {itemKey: "bakery:strawberry_glazed_cookie"},
    {itemKey: "bakery:sweetberry_glazed_cookie"},
    {itemKey: "bakery:chocolate_glazed_cookie"},
    {itemKey: "bakery:strawberry_cupcake"},
    {itemKey: "bakery:sweetberry_cupcake"},
    {itemKey: "bakery:apple_cupcake"},
    {itemKey: "beachparty:coconut_cocktail"},
    {itemKey: "beachparty:sweetberries_cocktail"},
    {itemKey: "beachparty:cocoa_cocktail"},
    {itemKey: "beachparty:pumpkin_cocktail"},
    {itemKey: "beachparty:melon_cocktail"},
    {itemKey: "beachparty:honey_cocktail"},
    {itemKey: "beachparty:sweetberry_milkshake"},
    {itemKey: "beachparty:sweetberry_icecream"},
    {itemKey: "beachparty:coconut_icecream"},
    {itemKey: "beachparty:chocolate_icecream"},
    {itemKey: "beachparty:icecream_coconut"},
    {itemKey: "beachparty:icecream_cactus"},
    {itemKey: "beachparty:icecream_chocolate"},
    {itemKey: "beachparty:icecream_sweetberries"},
    {itemKey: "beachparty:icecream_melon"},
    {itemKey: "meadow:cheesecake", countKey: 4},
    {itemKey: "meadow:cheese_tart", countKey: 3},
    {itemKey: "meadow:cheese_sandwich", countKey: 6},
    {itemKey: "meadow:cheese_roll", countKey: 8}
  ],
  3: [
    {itemKey: "aquaculturedelight:bass_stew"},
    {itemKey: "aquaculturedelight:unusual_fish_soup"},
    {itemKey: "aquaculturedelight:buckling"},
    {itemKey: "farmersdelight:stuffed_pumpkin_block"},
    {itemKey: "cuisinedelight:mixed_fried_rice"},
    {itemKey: "cuisinedelight:mixed_pasta"},
    {itemKey: "vinery:magnetic_wine"},
    {itemKey: "vinery:mellohi_wine"},
    {itemKey: "vinery:stal_wine"},
    {itemKey: "vinery:strad_wine"},
    {itemKey: "vinery:aegis_wine"},
    {itemKey: "vinery:clark_wine"},
    {itemKey: "vinery:kelp_cider"},
    {itemKey: "vinery:villagers_fright"},
    {itemKey: "vinery:eiswein"},
    {itemKey: "candlelight:tomato_soup"},
    {itemKey: "candlelight:mushroom_soup"},
    {itemKey: "candlelight:cooked_beef"},
    {itemKey: "candlelight:chicken_alfredo"},
    {itemKey: "candlelight:lettuce_beef"},
    {itemKey: "candlelight:salmon_wine", countKey: 2},
    {itemKey: "candlelight:pork_ribs", countKey: 4},
    {itemKey: "candlelight:chicken"},
    {itemKey: "candlelight:roastbeef_carrots"},
    {itemKey: "bakery:bread_crate"}
  ],
  4: [
    {itemKey: "vinery:jo_special_mixture"},
    {itemKey: "vinery:chorus_wine"},
    {itemKey: "vinery:cristel_wine"},
    {itemKey: "vinery:apple_wine"},
    {itemKey: "vinery:bolvar_wine"},
    {itemKey: "vinery:solaris_wine"},
    {itemKey: "vinery:chenet_wine"},
    {itemKey: "vinery:king_danis_wine"},
    {itemKey: "vinery:mead"},
    {itemKey: "meadow:sheep_cheese_block"},
    {itemKey: "meadow:grain_cheese_block"},
    {itemKey: "meadow:cheese_block"},
    {itemKey: "aquaculturedelight:halaszle"},
    {itemKey: "aquaculturedelight:rollmops"},
    {itemKey: "aquaculturedelight:baked_pollock_with_carrots"},
    {itemKey: "delightful:rock_candy"},
    {itemKey: "delightful:sinigang"},
    {itemKey: "delightful:ender_nectar"}
  ],
  5: [
    {itemKey: "candlelight:pasta"},
    {itemKey: "candlelight:bolognese"},
    {itemKey: "candlelight:fricasse"},
    {itemKey: "candlelight:pizza"},
    {itemKey: "meadow:buffalo_cheese_block"},
    {itemKey: "meadow:goat_cheese_block"},
    {itemKey: "meadow:amethyst_cheese_block"}
  ],
  6: [
    {itemKey: "candlelight:lasagne", countKey: 6},
    {itemKey: "candlelight:pasta_bolognese"},
    {itemKey: "aquaculturedelight:halibut_with_tartar_sauce"},
    {itemKey: "aquaculturedelight:poor_fisher_chowder"}
  ],
  9: [
    {itemKey: "candlelight:beef_wellington"}
  ],
  15: [
    {itemKey: "aquaculturedelight:tuna_spaghetti"},
    {itemKey: "aquaculture:turtle_soup"},
    {itemKey: "vinery:jellie_wine"}
  ]
}